// World weapons: China, Russia/USSR, Europe, USA, Japan, Korea, Israel.
// Art is built from templates of common layouts (AK, AR, battle rifle, bullpup,
// SMG, pistol, bolt sniper, classic rifle, GPMG, shotgun) with per-gun overrides.

const P = {
  pistol9: { power: 0.4, crack: 0.45, decay: 0.1, thump: 140, bright: 6200, tail: 0.4, mech: 'slide' },
  smg9: { power: 0.4, crack: 0.4, decay: 0.08, thump: 130, bright: 5800, tail: 0.35, mech: 'bolt-open' },
  full: { power: 0.82, crack: 0.9, decay: 0.24, thump: 78, bright: 7000, tail: 0.75, mech: 'gas' },
  ak: { power: 0.68, crack: 0.75, decay: 0.18, thump: 90, bright: 6300, tail: 0.6, mech: 'ak', steel: true },
  r545: { power: 0.6, crack: 0.92, decay: 0.15, thump: 112, bright: 8400, tail: 0.6, mech: 'ak', steel: true },
  r556: { power: 0.6, crack: 0.95, decay: 0.14, thump: 118, bright: 8800, tail: 0.55, mech: 'gas' },
  r58: { power: 0.62, crack: 0.95, decay: 0.14, thump: 114, bright: 8600, tail: 0.55, mech: 'gas', steel: true },
  shotgun: { power: 0.86, crack: 0.1, decay: 0.3, thump: 66, bright: 3400, tail: 0.8, mech: 'gas' },
};

function merge(base, o = {}) {
  const r = { ...base };
  for (const k of Object.keys(o)) {
    const v = o[k];
    r[k] = v && typeof v === 'object' && !Array.isArray(v) && base[k] && typeof base[k] === 'object' && !Array.isArray(base[k]) ? { ...base[k], ...v } : v;
    if (v === null) delete r[k];
  }
  return r;
}

const BASE = {
  ak: { kind: 'long', stock: { style: 'ak', x0: 0, x1: 240, top: 4, bot: 74, mat: 'wood' },
    rec: { x0: 240, x1: 560, top: -18, bot: 20, mat: 'blued', r: 2, port: [430, -10, 60, 10], lines: [[290, -18, 560, -18]] },
    grip: { x: 310, len: 76, ang: 16, w: 30, mat: 'wood' }, guard: { x: 360, w: 54, d: 22 },
    mag: { style: 'curved', x: 400, w: 44, len: 150, curve: 70, mat: 'blued' },
    fore: { style: 'ak', x0: 560, x1: 720, top: -8, bot: 16, mat: 'wood', ut: -28, ux: 700 }, gasTube: { x0: 700, x1: 790, h: 9 },
    barrel: { x0: 560, x1: 930, r: 5 }, muzzle: { style: 'ak', len: 26, r: 7 }, fsight: { x: 905, h: 30 }, rsight: { x: 548, h: 26, w: 26, y: -16 },
    bolt: { style: 'tab', x: 500, y: -10, w: 26, h: 9 }, eject: { x: 460, y: -18 } },
  ar: { kind: 'long', stock: { style: 'tube', x0: 0, x1: 250, top: -16, bot: 52, mat: 'poly' },
    rec: { x0: 250, x1: 480, top: -22, bot: 18, mat: 'poly', r: 3, rail: [254, 476], port: [380, -12, 48, 12], lower: 'M270 18 L440 18 L440 36 L270 36 Z', lowerMat: 'poly' },
    grip: { x: 330, len: 76, ang: 20, w: 30, mat: 'poly' }, guard: { x: 375, y: 36, w: 54, d: 20 },
    mag: { style: 'curved', x: 400, w: 42, len: 120, curve: 22, y: 32, mat: 'poly' },
    fore: { style: 'rail', x0: 480, x1: 690, top: -20, bot: 18, mat: 'poly' }, barrel: { x0: 480, x1: 820, r: 5 }, muzzle: { style: 'flash', len: 34, r: 7 },
    fsight: { x: 700, h: 46 }, bolt: { style: 'tab', x: 262, y: -30, w: 20, h: 8 }, eject: { x: 400, y: -12 } },
  battle: { kind: 'long', stock: { style: 'fixed', x0: 0, x1: 250, top: -4, bot: 70, mat: 'wooddark' },
    rec: { x0: 250, x1: 540, top: -22, bot: 18, mat: 'blued', r: 3, port: [410, -12, 60, 12] },
    grip: { x: 330, len: 76, ang: 16, w: 30, mat: 'poly' }, guard: { x: 375, w: 54, d: 22 },
    mag: { style: 'box', x: 420, w: 50, len: 100, ang: 6, mat: 'blued' },
    fore: { style: 'wood', x0: 540, x1: 740, top: -16, bot: 18, mat: 'wooddark' }, barrel: { x0: 540, x1: 950, r: 5 }, muzzle: { style: 'flash', len: 40, r: 8 },
    fsight: { x: 790, h: 34 }, rsight: { x: 500, h: 34, w: 24, y: -22 }, bolt: { style: 'tab', x: 520, y: -14, w: 20, h: 9 }, eject: { x: 440, y: -12 } },
  bullpup: { kind: 'long', k: 1.25,
    rec: { x0: 0, x1: 600, top: -26, bot: 22, mat: 'poly', r: 6, shape: 'M0 -18 Q0 -26 10 -26 L560 -26 L600 -14 L600 22 L480 22 L470 26 L440 26 L425 72 L370 74 L355 28 L300 30 L290 62 L40 70 Q0 70 0 52 Z' },
    grip: { x: 480, len: 74, ang: 10, w: 32, mat: 'poly' }, guard: { x: 520, y: 22, w: 64, d: 26, mat: 'poly' },
    mag: { style: 'curved', x: 220, w: 42, len: 110, curve: 22, y: 60, mat: 'poly', behind: true },
    barrel: { x0: 600, x1: 780, r: 6 }, muzzle: { style: 'flash', len: 32, r: 8 }, fore: { style: 'plain', x0: 600, x1: 650, top: -14, bot: 14, mat: 'poly' },
    bolt: { style: 'tab', x: 360, y: -20, w: 18, h: 8 }, eject: { x: 250, y: -16 }, extras: [['rect', -10, -22, 12, 92, 'rubber', 4]] },
  smg: { kind: 'long', stock: { style: 'fixed', x0: 0, x1: 200, top: -12, bot: 56, mat: 'poly', joinT: 4 },
    rec: { x0: 200, x1: 470, top: -22, bot: 14, mat: 'poly', r: 4, port: [330, -12, 44, 12], lower: 'M230 14 L400 14 L400 30 L230 30 Z', lowerMat: 'poly' },
    grip: { x: 290, len: 74, ang: 14, w: 30, mat: 'poly' }, guard: { x: 340, y: 30, w: 54, d: 20 },
    mag: { style: 'curved', x: 380, w: 34, len: 120, curve: 34, y: 10, mat: 'blued' },
    fore: { style: 'plain', x0: 470, x1: 590, top: -16, bot: 18, mat: 'poly', r: 10 }, barrel: { x0: 470, x1: 660, r: 6 }, muzzle: { style: 'bayonetlug', len: 14, r: 7 },
    rsight: { x: 210, h: 40, w: 22, y: -22 }, fsight: { x: 620, h: 36 }, bolt: { style: 'tab', x: 560, y: -34, w: 16, h: 10 }, eject: { x: 350, y: -12 } },
  pistol: { kind: 'pistol', slide: { x0: 0, x1: 290, top: -28, bot: 4, mat: 'poly', serr: 8, port: [118, 48] },
    frame: { x0: 4, x1: 282, top: 4, bot: 26, mat: 'poly', guardX: 158 }, grip: { x0: 10, x1: 86, y: 22, len: 120, ang: 18, mat: 'poly' }, magBase: 'poly', eject: { x: 140, y: -28 } },
  boltSniper: { kind: 'long', stock: { style: 'thumbhole', x0: 0, x1: 300, top: -14, bot: 76, mat: 'olive', cheek: true },
    rec: { x0: 300, x1: 520, top: -18, bot: 16, mat: 'blued', r: 4, rail: [310, 510] }, guard: { x: 420, w: 54, d: 22 },
    mag: { style: 'box', x: 440, w: 44, len: 50, mat: 'dark' }, fore: { style: 'plain', x0: 520, x1: 760, top: -14, bot: 20, mat: 'olive', r: 6 },
    barrel: { x0: 520, x1: 1060, r: 6 }, muzzle: { style: 'comp', len: 40, r: 9 },
    optic: { style: 'scope', x0: 300, x1: 560, y: -54, r: 9, eb: 15, ob: 18, base: -18, rings: [340, 470] },
    bipod: { x: 720, len: 100, y: 20, splay: 18 }, bolt: { style: 'knob', x: 480, drop: 24 }, eject: { x: 440, y: -16 } },
  classic: { kind: 'long', stock: { style: 'classic', x0: 0, top: 6, bot: 92, wrist: 260, guard: 400, fore: 900, mat: 'wood', upper: [470, 880], bands: [620, 870] },
    rec: { x0: 330, x1: 470, top: -14, bot: 10, mat: 'blued' }, mag: { style: 'internal', x: 410, w: 60, y: 14, mat: 'blued' },
    guard: { x: 410, y: 22, w: 64, d: 22 }, barrel: { x0: 470, x1: 950, r: 5 }, muzzle: { style: 'bayonetlug', len: 22 },
    fsight: { x: 935, h: 22 }, rsight: { x: 500, h: 14, w: 26, y: -4 }, bolt: { style: 'knob', x: 362, drop: 20 }, eject: { x: 385, y: -14 } },
  gpmg: { kind: 'long', stock: { style: 'mg', x0: 0, x1: 210, top: -12, bot: 62, mat: 'poly' },
    rec: { x0: 210, x1: 520, top: -26, bot: 16, mat: 'park', r: 4 }, grip: { x: 340, len: 70, ang: 12, w: 30, mat: 'poly' }, guard: { x: 370, w: 52, d: 22 },
    mag: { style: 'belt', x: 440, len: 120, n: 9, sweep: 30 }, fore: { style: 'plain', x0: 520, x1: 680, top: -18, bot: 22, mat: 'poly' },
    barrel: { x0: 520, x1: 960, r: 7, mat: 'park' }, muzzle: { style: 'flash', len: 34, r: 9 }, gasTube: { x0: 680, x1: 830, h: 10 },
    fsight: { x: 920, h: 30 }, rsight: { x: 470, h: 40, w: 22, y: -26 }, bipod: { x: 840, len: 110, y: 10, splay: 20 }, eject: { x: 400, y: 16 }, ejectDown: true,
    extras: [['rect', 560, -46, 60, 10, 'park', 4], ['rect', 580, -38, 8, 14, 'park', 1]] },
  shotgun: { kind: 'long', stock: { style: 'fixed', x0: 0, x1: 300, top: -6, bot: 76, mat: 'poly' },
    rec: { x0: 300, x1: 470, top: -18, bot: 22, mat: 'blued', r: 4, port: [380, -8, 60, 14] }, grip: { x: 360, len: 74, ang: 22, w: 34, mat: 'poly' }, guard: { x: 400, w: 54, d: 22 },
    tube: { x: 470, w: 14, len: 330, y: 9, mat: 'blued' }, fore: { style: 'plain', x0: 470, x1: 640, top: -14, bot: 28, mat: 'poly', r: 6 },
    barrel: { x0: 470, x1: 930, r: 8 }, muzzle: { style: 'none' }, fsight: { x: 920, h: 14 }, eject: { x: 410, y: -8 } },
};
const A = Object.fromEntries(Object.keys(BASE).map((k) => [k, (o) => merge(BASE[k], o)]));

// shorthand constructor
const W = (o) => ({ eras: ['modern'], trivia: [], nickname: '', ...o });

export const WORLD = [
  // ================================================================ CHINA
  W({ id: 'type56', name: 'Type 56', nickname: 'Chinese AK', type: 'rifle', country: 'China', year: 1956, designer: 'Norinco (licensed AK-47)', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Sino-Vietnamese War', 'Conflicts across Asia & Africa'], caliber: '7.62×39mm', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30,
    rpm: 650, weight: '3.8 kg', length: '874 mm', velocity: '735 m/s', range: '300 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'China\'s licensed copy of the AK-47 — one of the most produced firearms in history. Many versions carry a permanently attached folding spike bayonet.',
    how: ['Long-stroke piston fixed to the bolt carrier, AK-style.', 'The carrier rotates the bolt to unlock, extracts and ejects.', 'A hooded front sight distinguishes it from Soviet AKs.', 'The spike bayonet folds under the barrel.'],
    history: 'Produced from 1956 with Soviet help, it armed the People\'s Liberation Army for decades and was exported in millions to Asia and Africa.',
    feel: { recoil: 6, loud: 8, text: 'Classic AK shove and harsh crack; slightly heavier than a Soviet AK.' }, trivia: ['Millions were exported, making it one of the most common AKs worldwide.'],
    sound: { ...P.ak, thump: 92 }, mv: 735, eff: 300, max: 3000, bulletG: 7.9, moa: '3–5 MOA', heat: 3, heatNote: 'No quick-change barrel; practical ~100 rpm in bursts.', env: [5, 5, 5, 5, 5], users: ['army', 'police'], cart: '762x39',
    art: A.ak({ muzzle: { style: 'none' }, fsight: { x: 915, h: 34 }, extras: [['rect', 760, 6, 160, 5, 'blued', 2]] }) }),
  W({ id: 'qbz95', name: 'QBZ-95', nickname: 'Type 95', type: 'rifle', country: 'China', year: 1995, designer: 'Norinco', wars: ['PLA service', 'Hong Kong handover garrison (1997)'],
    caliber: '5.8×42mm DBP87', action: 'Gas-operated short-stroke piston, rotating bolt, bullpup', capacity: 30, rpm: 650, weight: '3.25 kg', length: '745 mm', velocity: '930 m/s', range: '400 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'China\'s distinctive bullpup service rifle, firing its own 5.8mm cartridge. It was the PLA\'s standard rifle from the late 1990s.',
    how: ['Bullpup: the magazine sits behind the grip, keeping the rifle short.', 'A short-stroke piston drives a rotating bolt.', 'A large carry handle holds the iron sights and optic mounts.', 'The 5.8×42mm round was designed to rival 5.56 and 5.45mm.'],
    history: 'Introduced in 1995 and first seen widely when PLA troops entered Hong Kong in 1997. It is being replaced by the conventional QBZ-191.',
    feel: { recoil: 3, loud: 8, text: 'Mild recoil straight into the shoulder; a sharp, high crack close to your cheek.' }, trivia: ['Reloading happens near the shoulder, behind the pistol grip.'],
    sound: P.r58, mv: 930, eff: 400, max: 3500, bulletG: 4.15, moa: '2–4 MOA', heat: 3, heatNote: 'Short barrel heats in sustained automatic fire.', env: [4, 4, 4, 3, 4], users: ['army', 'navy', 'airforce', 'police'], cart: '58x42',
    art: A.bullpup({ optic: { style: 'aug', x0: 250, x1: 560, y: -26, mat: 'poly' } }) }),
  W({ id: 'qbz191', name: 'QBZ-191', type: 'rifle', country: 'China', year: 2019, designer: 'Norinco', wars: ['PLA service (since 2019)'],
    caliber: '5.8×42mm', action: 'Gas-operated short-stroke piston, rotating bolt', capacity: 30, rpm: 750, weight: '~3.5 kg', length: '~920 mm', velocity: '~930 m/s', range: '400 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'China\'s new conventional-layout service rifle, first shown at the 2019 National Day parade. AR-style ergonomics, rails and an adjustable stock replace the bullpup layout.',
    how: ['Short-stroke piston with a rotating bolt.', 'Full-length top rail for optics; telescoping stock.', 'Conventional layout makes ambidextrous use and reloads easier than the QBZ-95.'],
    history: 'Unveiled in 2019 and progressively replacing the QBZ-95 across the PLA. Published details are limited.',
    feel: { recoil: 3, loud: 8, text: 'Controlled, flat-shooting 5.8mm with modern ergonomics.' }, trivia: ['Published performance figures are limited; values are approximate.'],
    sound: P.r58, mv: 930, eff: 400, max: 3500, bulletG: 4.15, moa: '2–3 MOA', heat: 3, heatNote: 'Typical for a piston carbine.', env: [4, 4, 4, 3, 4], users: ['army', 'navy'], cart: '58x42',
    art: A.ar({ optic: { style: 'reddot', x0: 300, y: -30 }, fsight: null, rec: { mat: 'park' } }) }),
  W({ id: 'qsz92', name: 'QSZ-92', type: 'pistol', country: 'China', year: 1998, designer: 'Norinco', wars: ['PLA & People\'s Armed Police service'],
    caliber: '9×19mm (also 5.8×21mm)', action: 'Short recoil, rotating barrel', capacity: 15, rpm: null, weight: '0.76 kg', length: '190 mm', velocity: '~350 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'China\'s standard military pistol, with a polymer frame and a rotating-barrel lock.',
    how: ['The barrel rotates to unlock from the slide as they recoil together.', 'Polymer frame with an accessory rail.', 'Double-stack 15-round magazine.'],
    history: 'Adopted in 1998, replacing the Type 54 (Tokarev) and Type 59 (Makarov) pistols.',
    feel: { recoil: 4, loud: 6, text: 'Smooth and straight-back thanks to the rotating barrel.' },
    sound: P.pistol9, mv: 350, eff: 50, max: 1800, bulletG: 8, moa: '3–5 MOA', heat: 1, heatNote: 'Sidearm — heat is not a factor.', env: [4, 4, 4, 3, 4], users: ['army', 'police'], cart: '9x19',
    art: A.pistol({ slide: { mat: 'blued' } }) }),
  W({ id: 'qbu88', name: 'QBU-88', nickname: 'Type 88 sniper rifle', type: 'sniper', country: 'China', year: 1997, designer: 'Norinco', wars: ['PLA service'],
    caliber: '5.8×42mm (heavy DBP88)', action: 'Gas-operated short-stroke piston, rotating bolt, bullpup', capacity: 10, rpm: null, weight: '4.1 kg', length: '920 mm', velocity: '895 m/s', range: '800 m',
    modes: ['semi'], ammo: 'rifle',
    overview: 'A bullpup designated marksman rifle firing a heavy-bullet 5.8mm round, giving each PLA squad longer reach.',
    how: ['Bullpup layout keeps a long barrel in a compact rifle.', 'Short-stroke gas piston, semi-automatic only.', 'Scope and bipod for precise long-range fire.'],
    history: 'Introduced in the late 1990s alongside the QBZ-95 family.',
    feel: { recoil: 4, loud: 8, text: 'Light recoil for a marksman rifle; fast, precise follow-up shots.' },
    sound: { ...P.r58, power: 0.66, decay: 0.17 }, mv: 895, eff: 800, max: 3500, bulletG: 5, moa: '~1.5 MOA', heat: 2, heatNote: 'Precision fire keeps heat low.', env: [4, 4, 4, 3, 4], users: ['army', 'police'], cart: '58x42',
    art: A.bullpup({ barrel: { x1: 900 }, mag: { style: 'box', len: 60, curve: 0 }, optic: { style: 'scope', x0: 300, x1: 560, y: -56, r: 9, eb: 14, ob: 17, base: -26, rings: [350, 460] }, bipod: { x: 720, len: 100, y: 10, splay: 18 } }) }),

  // ================================================================ RUSSIA / USSR
  W({ id: 'ak74', name: 'AK-74', type: 'rifle', country: 'USSR', year: 1974, designer: 'Mikhail Kalashnikov', eras: ['cold', 'modern'],
    wars: ['Soviet–Afghan War', 'Chechen Wars', 'Russo-Ukrainian War'], caliber: '5.45×39mm', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30, rpm: 650,
    weight: '3.3 kg', length: '943 mm', velocity: '900 m/s', range: '500 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'The Soviet move to a small, fast 5.45mm round. A large two-chamber muzzle brake makes it remarkably flat-shooting in automatic.',
    how: ['Same rugged AK long-stroke action.', 'The muzzle brake vents gas sideways and up, cancelling much of the recoil.', 'The lighter round lets soldiers carry more ammunition.', 'Iconic orange-brown "plum" magazines.'],
    history: 'Replaced the AKM from 1974 and first saw combat in Afghanistan. Still widely used by Russian and former-Soviet forces.',
    feel: { recoil: 3, loud: 9, text: 'Barely moves in automatic — but the brake makes it painfully loud for anyone beside you.' }, trivia: ['The 5.45mm bullet has a small air pocket in its tip.'],
    sound: P.r545, mv: 900, eff: 500, max: 3150, bulletG: 3.4, moa: '2–4 MOA', heat: 3, heatNote: 'No quick-change barrel; practical ~100 rpm in bursts.', env: [5, 5, 5, 5, 5], users: ['army', 'police', 'sf'], cart: '545x39',
    art: A.ak({ stock: { mat: 'woodred' }, grip: { mat: 'woodred' }, fore: { mat: 'woodred' }, mag: { mat: 'woodred', curve: 50, len: 140 }, muzzle: { style: 'comp', len: 46, r: 8 } }) }),
  W({ id: 'ak12', name: 'AK-12', type: 'rifle', country: 'Russia', year: 2018, designer: 'Kalashnikov Concern', wars: ['Russo-Ukrainian War'],
    caliber: '5.45×39mm', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30, rpm: 700, weight: '3.5 kg', length: '945 mm', velocity: '880 m/s', range: '500 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'Russia\'s current-generation Kalashnikov: rails for optics, a telescoping folding stock and improved ergonomics on the proven AK action.',
    how: ['AK long-stroke piston and rotating bolt.', 'A rigid, hinged top cover holds a full-length rail.', 'Adjustable folding stock and ambidextrous controls.', 'Early versions offered a 2-round burst.'],
    history: 'Adopted by the Russian Army in 2018 after years of development to replace the AK-74M.',
    feel: { recoil: 3, loud: 9, text: 'Flat-shooting 5.45 with a modern feel; loud brake.' },
    sound: { ...P.r545, power: 0.62 }, mv: 880, eff: 500, max: 3150, bulletG: 3.4, moa: '2–3 MOA', heat: 3, heatNote: 'Similar to the AK-74.', env: [5, 5, 5, 4, 5], users: ['army', 'sf'], cart: '545x39',
    art: A.ak({ stock: { style: 'fixed', x0: 0, x1: 240, top: -8, bot: 60, mat: 'poly' }, grip: { mat: 'poly' }, fore: { style: 'mlok', x0: 560, x1: 760, top: -18, bot: 18, mat: 'poly' }, gasTube: null, rec: { rail: [300, 555] }, mag: { mat: 'poly', curve: 50, len: 140 }, muzzle: { style: 'comp', len: 40, r: 8 }, optic: { style: 'reddot', x0: 330, y: -24 }, rsight: null }) }),
  W({ id: 'pm', name: 'Makarov PM', type: 'pistol', country: 'USSR', year: 1951, designer: 'Nikolay Makarov', eras: ['cold', 'modern'],
    wars: ['Soviet & Warsaw Pact service', 'Russian police & military'], caliber: '9×18mm Makarov', action: 'Straight blowback, double action', capacity: 8, rpm: null,
    weight: '0.73 kg', length: '161 mm', velocity: '315 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'A compact, simple and extremely reliable Soviet sidearm — with only around 27 parts — issued for over 50 years.',
    how: ['Simple blowback: the slide is held closed only by spring and mass.', 'Fixed barrel for good accuracy.', 'Double-action first shot, then single action.', 'The 9×18mm round is the strongest practical for blowback.'],
    history: 'Adopted in 1951 and made in huge numbers across the Eastern Bloc; it is still carried by many police forces.',
    feel: { recoil: 5, loud: 6, text: 'Snappy for its size — blowback pistols kick sharper than locked-breech ones.' },
    sound: { ...P.pistol9, power: 0.38, crack: 0.1, decay: 0.09 }, mv: 315, eff: 50, max: 1600, bulletG: 6.1, moa: '4–6 MOA', heat: 1, heatNote: 'Sidearm — no heat concerns.', env: [4, 5, 4, 4, 4], users: ['army', 'police'], cart: '9x18',
    art: A.pistol({ hammer: true, slide: { x0: 0, x1: 220, top: -24, bot: 4, mat: 'blued', serr: 7, port: [100, 36] }, frame: { x0: 4, x1: 200, top: 4, bot: 24, mat: 'blued', guardX: 132 }, grip: { x0: 14, x1: 78, y: 20, len: 100, ang: 14, mat: 'woodred', panel: 'woodred' }, magBase: 'blued', eject: { x: 110, y: -24 } }) }),
  W({ id: 'rpk', name: 'RPK', type: 'lmg', country: 'USSR', year: 1961, designer: 'Mikhail Kalashnikov', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Soviet–Afghan War', 'Many conflicts worldwide'], caliber: '7.62×39mm', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 40,
    rpm: 600, weight: '4.8 kg', length: '1,040 mm', velocity: '745 m/s', range: '800 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'An AK stretched into a squad light machine gun: longer, heavier barrel, bipod and 40-round magazine — but it shares magazines and parts with every AK.',
    how: ['Same AK action, with a heavier receiver and barrel.', 'Folding bipod near the muzzle.', 'Takes 40-round box or 75-round drum magazines — and any AK magazine.', 'No quick-change barrel: fire discipline is needed.'],
    history: 'Replaced the RPD in 1961. Its 5.45mm sibling, the RPK-74, followed in 1974.',
    feel: { recoil: 4, loud: 8, text: 'AK punch tamed by extra weight; steady automatic fire from the bipod.' },
    sound: P.ak, mv: 745, eff: 800, max: 3000, bulletG: 7.9, moa: '3–5 MOA (bipod)', heat: 4, heatNote: 'No quick-change barrel — limited to bursts.', env: [5, 5, 5, 5, 5], users: ['army'], cart: '762x39',
    art: A.ak({ barrel: { x1: 1060 }, muzzle: { style: 'none' }, fsight: { x: 1040, h: 30 }, mag: { len: 190, curve: 80 }, bipod: { x: 960, len: 100, y: 6, splay: 16 } }) }),
  W({ id: 'vss', name: 'VSS Vintorez', nickname: '"Thread cutter"', type: 'sniper', country: 'USSR', year: 1987, designer: 'Pyotr Serdyukov (TsNIITochMash)', eras: ['cold', 'modern'],
    wars: ['Chechen Wars', 'Syrian Civil War', 'Russo-Ukrainian War'], caliber: '9×39mm (subsonic)', action: 'Gas-operated, rotating bolt, integral suppressor', capacity: 10,
    rpm: 800, weight: '2.6 kg', length: '894 mm', velocity: '290 m/s', range: '400 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'An integrally suppressed special-forces sniper rifle. Its heavy subsonic bullets make no supersonic crack, and the built-in suppressor hides almost all flash and blast.',
    how: ['The barrel is ported inside a large suppressor that slows and cools the gas.', 'Heavy 9mm bullets stay below the speed of sound — no crack.', 'Gas-operated rotating bolt; can fire automatic in emergencies.', 'What you mostly hear is the action cycling.'],
    history: 'Developed for Soviet special forces in the 1980s. It is still used by Russian special units.',
    feel: { recoil: 3, loud: 2, text: 'A soft "thup" and the clack of the bolt — eerily quiet compared with any other rifle here.' }, trivia: ['Its name refers to the rifling ("thread") inside the barrel.'],
    sound: { power: 0.25, crack: 0, decay: 0.05, thump: 150, bright: 2200, tail: 0.15, mech: 'ak', suppressed: true }, mv: 290, eff: 400, max: 1800, bulletG: 16, moa: '~2 MOA', heat: 3, heatNote: 'The suppressor heats fast in automatic.', env: [4, 4, 4, 3, 4], users: ['sf', 'army'], cart: '9x39',
    art: A.ak({ stock: { style: 'thumbhole', x0: 0, x1: 240, top: -10, bot: 70, mat: 'wood' }, grip: null, mag: { style: 'box', len: 70, ang: 6, w: 44 }, fore: { style: 'plain', x0: 560, x1: 640, top: -16, bot: 16, mat: 'blued' }, gasTube: null, barrel: { x0: 560, x1: 940, r: 15, mat: 'blued' }, muzzle: { style: 'none' }, fsight: null, optic: { style: 'pso', x0: 320, x1: 520, y: -50, base: -18 }, rsight: null }) }),

  // ================================================================ EUROPE
  W({ id: 'g3', name: 'Heckler & Koch G3', type: 'rifle', country: 'West Germany', year: 1959, designer: 'Heckler & Koch', eras: ['cold', 'modern'],
    wars: ['Portuguese Colonial War', 'Iran–Iraq War', 'Many conflicts worldwide'], caliber: '7.62×51mm NATO', action: 'Roller-delayed blowback', capacity: 20, rpm: 550,
    weight: '4.4 kg', length: '1,025 mm', velocity: '800 m/s', range: '500 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'West Germany\'s battle rifle and the parent of the MP5. Used by over 50 countries; famous for throwing its brass a long way.',
    how: ['Two rollers in the bolt head delay opening until pressure drops.', 'No gas system — fewer parts to foul.', 'A fluted chamber lets the case "float" for extraction.', 'Rotating drum rear sight with range settings.'],
    history: 'Adopted by the Bundeswehr in 1959, replaced by the G36 in the late 1990s. Licence-built in Pakistan, Iran, Turkey and many more.',
    feel: { recoil: 8, loud: 9, text: 'A sharp, hard-hitting 7.62 kick; cases fly several metres to the side.' },
    sound: { ...P.full, mech: 'roller' }, mv: 800, eff: 500, max: 3725, bulletG: 9.5, moa: '2–3 MOA', heat: 3, heatNote: 'Heavy rounds heat the barrel in automatic.', env: [4, 4, 4, 3, 4], users: ['army', 'police'], cart: '762x51',
    art: A.battle({ stock: { mat: 'poly' }, fore: { style: 'plain', mat: 'poly', r: 6 }, mag: { style: 'curved', curve: 18, len: 110, w: 46 }, extras: [['rect', 300, -38, 22, 16, 'blued', 3]] }) }),
  W({ id: 'hk416', name: 'Heckler & Koch HK416', type: 'rifle', country: 'Germany', year: 2005, designer: 'Heckler & Koch',
    wars: ['War in Afghanistan', 'Operation Neptune Spear (2011)', 'Operations in Mali & Iraq'], caliber: '5.56×45mm NATO', action: 'Short-stroke gas piston, rotating bolt', capacity: 30, rpm: 850,
    weight: '3.5 kg', length: '~900 mm', velocity: '~880 m/s', range: '500 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'An AR-15 rebuilt with a piston system for reliability. Adopted by special forces worldwide, France, Norway and — as the M27 — the US Marine Corps.',
    how: ['A short-stroke piston replaces the AR\'s direct gas impingement, keeping the action cleaner and cooler.', 'Familiar AR controls and magazines.', 'Free-floating rail handguard.', 'Over-the-beach capability — it can fire after being submerged and drained.'],
    history: 'Developed with input from US special operators and widely reported in the 2011 raid on Osama bin Laden\'s compound.',
    feel: { recoil: 3, loud: 8, text: 'Smooth and flat; a sharp crack without the gassy AR "sproing".' },
    sound: { ...P.r556, mech: 'gas' }, mv: 880, eff: 500, max: 3600, bulletG: 4, moa: '1.5–2.5 MOA', heat: 3, heatNote: 'Piston keeps the action cooler than an AR.', env: [4, 4, 4, 4, 4], users: ['sf', 'army', 'navy'], cart: '556x45',
    art: A.ar({ fore: { x1: 720 }, barrel: { x1: 850 }, fsight: null, optic: { style: 'reddot', x0: 300, y: -30 }, rec: { mat: 'park' } }) }),
  W({ id: 'g36', name: 'Heckler & Koch G36', type: 'rifle', country: 'Germany', year: 1997, designer: 'Heckler & Koch',
    wars: ['Kosovo', 'War in Afghanistan'], caliber: '5.56×45mm NATO', action: 'Short-stroke gas piston, rotating bolt', capacity: 30, rpm: 750,
    weight: '3.6 kg', length: '999 mm', velocity: '920 m/s', range: '500 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A light, largely polymer rifle with a built-in carry handle optic and translucent magazines that clip together. Germany\'s service rifle for over 20 years.',
    how: ['Short-stroke piston drives a rotating bolt (AR-18 style).', 'Glass-fibre-reinforced polymer receiver.', 'Integrated optic in the carry handle.', 'Side-folding skeleton stock.'],
    history: 'Adopted by the Bundeswehr in 1997. After reports of accuracy loss when very hot, Germany chose the HK416 successor (G95).',
    feel: { recoil: 3, loud: 8, text: 'Light and soft-shooting; a crisp 5.56 crack.' },
    sound: { ...P.r556, mech: 'gas' }, mv: 920, eff: 500, max: 3600, bulletG: 4, moa: '2–3 MOA', heat: 4, heatNote: 'Reported accuracy drift when the barrel area gets very hot.', env: [4, 4, 3, 3, 4], users: ['army', 'police', 'sf'], cart: '556x45',
    art: A.ar({ stock: { style: 'skeleton', x0: 0, x1: 250, top: -16, bot: 56, mat: 'poly' }, rec: { rail: null }, mag: { mat: 'clear', curve: 30 }, fore: { style: 'plain', x0: 480, x1: 700, top: -18, bot: 18, mat: 'poly', r: 6 }, optic: { style: 'aug', x0: 280, x1: 470, y: -22, mat: 'poly' }, fsight: null, barrel: { x1: 860 } }) }),
  W({ id: 'scarh', name: 'FN SCAR-H', nickname: 'Mk 17', type: 'rifle', country: 'Belgium', year: 2009, designer: 'FN Herstal',
    wars: ['War in Afghanistan', 'Iraq'], caliber: '7.62×51mm NATO', action: 'Short-stroke gas piston, rotating bolt', capacity: 20, rpm: 600,
    weight: '3.6 kg', length: '~1,000 mm', velocity: '~800 m/s', range: '600 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A modular special-operations battle rifle in flat dark earth: quick-change barrels, folding stock and full-length rails.',
    how: ['Short-stroke piston with a rotating bolt.', 'Barrel lengths can be swapped by the user.', 'Side-folding, adjustable stock.', 'Non-reciprocating charging handle on the side.'],
    history: 'Developed for US Special Operations Command in the 2000s and fielded around 2009; adopted by several other countries.',
    feel: { recoil: 6, loud: 9, text: 'Surprisingly soft for a 7.62 rifle thanks to its recoil buffer.' },
    sound: { ...P.full, mech: 'gas', power: 0.8 }, mv: 800, eff: 600, max: 3725, bulletG: 9.5, moa: '1.5–2.5 MOA', heat: 3, heatNote: 'Quick-change barrel helps.', env: [4, 4, 4, 4, 4], users: ['sf', 'army'], cart: '762x51',
    art: A.ar({ stock: { style: 'skeleton', x0: 0, x1: 250, top: -16, bot: 56, mat: 'fde' }, rec: { mat: 'fde', lowerMat: 'poly' }, fore: { style: 'rail', x0: 480, x1: 720, top: -22, bot: 18, mat: 'fde' }, mag: { style: 'box', w: 46, len: 100, ang: 5, mat: 'poly' }, barrel: { x1: 880, r: 6 }, fsight: null, optic: { style: 'reddot', x0: 290, y: -30 } }) }),
  W({ id: 'famas', name: 'FAMAS F1', nickname: 'Le Clairon — "The Bugle"', type: 'rifle', country: 'France', year: 1978, designer: 'Paul Télie (MAS)', eras: ['cold', 'modern'],
    wars: ['Gulf War', 'War in Afghanistan', 'Operations in Mali'], caliber: '5.56×45mm NATO', action: 'Lever-delayed blowback, bullpup', capacity: 25, rpm: 1000,
    weight: '3.6 kg', length: '757 mm', velocity: '960 m/s', range: '300 m', modes: ['semi', 'burst', 'auto'], ammo: 'rifle',
    overview: 'France\'s iconic bullpup with a long carry handle — nicknamed "the bugle". Very fast-firing at around 1,000 rpm.',
    how: ['A lever delays the bolt\'s opening — no gas system.', 'Bullpup layout behind the trigger.', 'The long carry handle protects the sights.', 'Mechanical 3-round burst plus automatic.'],
    history: 'Adopted in 1978 and used by French forces for four decades until replaced by the HK416F.',
    feel: { recoil: 3, loud: 9, text: 'A fast, ripping burst right beside your ear.' },
    sound: { ...P.r556, mech: 'roller' }, mv: 960, eff: 300, max: 3600, bulletG: 4, moa: '2–3 MOA', heat: 3, heatNote: 'Very high cyclic rate heats it quickly in auto.', env: [3, 4, 4, 3, 4], users: ['army', 'navy', 'airforce'], cart: '556x45',
    art: A.bullpup({ optic: { style: 'carry', x0: 130, x1: 570, y: -26 }, mag: { style: 'box', len: 70, w: 40 }, barrel: { x1: 760 } }) }),
  W({ id: 'beretta92', name: 'Beretta 92FS / M9', type: 'pistol', country: 'Italy', year: 1975, designer: 'Beretta', eras: ['cold', 'modern'],
    wars: ['Gulf War', 'Iraq War', 'War in Afghanistan'], caliber: '9×19mm Parabellum', action: 'Short recoil, falling locking block', capacity: 15, rpm: null,
    weight: '0.95 kg', length: '217 mm', velocity: '381 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'The open-slide Italian pistol that replaced the M1911 as the US M9 in 1985 — and a Hollywood favourite.',
    how: ['A locking block under the barrel drops to unlock — the barrel never tilts.', 'Open-top slide gives reliable ejection.', 'Double action first shot, then single action.'],
    history: 'Introduced in 1975; won US trials in 1985 and served as the M9 until the M17 replaced it.',
    feel: { recoil: 4, loud: 6, text: 'Heavy and soft-shooting; very straight recoil.' },
    sound: P.pistol9, mv: 381, eff: 50, max: 1800, bulletG: 8, moa: '3–4 MOA', heat: 1, heatNote: 'Sidearm — no heat concerns.', env: [4, 4, 4, 3, 4], users: ['army', 'navy', 'airforce', 'police'], cart: '9x19',
    art: A.pistol({ hammer: true, barrelOut: 14, slide: { x0: 0, x1: 296, top: -26, bot: 4, mat: 'blued', serr: 8, port: [120, 120] }, frame: { x0: 6, x1: 250, top: 4, bot: 26, mat: 'blued', guardX: 160 }, grip: { x0: 16, x1: 90, y: 22, len: 126, ang: 12, mat: 'poly', panel: 'poly' }, magBase: 'blued' }) }),
  W({ id: 'p226', name: 'SIG Sauer P226', type: 'pistol', country: 'Switzerland / Germany', year: 1984, designer: 'SIG Sauer', eras: ['cold', 'modern'],
    wars: ['US Navy SEAL service', 'Special & police units worldwide'], caliber: '9×19mm Parabellum', action: 'Short recoil, tilting barrel, DA/SA', capacity: 15, rpm: null,
    weight: '0.96 kg', length: '196 mm', velocity: '~350 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'A premium service pistol renowned for accuracy and reliability — the long-time sidearm of the US Navy SEALs.',
    how: ['Browning-type tilting barrel locked into the ejection port.', 'Decocking lever instead of a manual safety.', 'Double-stack 15-round magazine.'],
    history: 'Designed for the 1980s US pistol trials; though the Beretta won on price, the P226 became a favourite of special units and police worldwide.',
    feel: { recoil: 4, loud: 6, text: 'Solid, controllable and accurate.' },
    sound: { ...P.pistol9, thump: 135 }, mv: 350, eff: 50, max: 1800, bulletG: 8, moa: '2–3 MOA', heat: 1, heatNote: 'Sidearm — no heat concerns.', env: [4, 4, 4, 3, 4], users: ['sf', 'navy', 'police'], cart: '9x19',
    art: A.pistol({ hammer: true, slide: { mat: 'blued', serr: 9 }, frame: { mat: 'blued', x1: 270 }, grip: { x0: 14, x1: 88, y: 22, len: 124, ang: 14, mat: 'poly', panel: 'poly' }, magBase: 'blued' }) }),
  W({ id: 'scorpion', name: 'CZ Scorpion EVO 3', type: 'smg', country: 'Czech Republic', year: 2009, designer: 'Česká zbrojovka',
    wars: ['Police & special units'], caliber: '9×19mm Parabellum', action: 'Straight blowback, closed bolt', capacity: 30, rpm: 1150,
    weight: '2.77 kg', length: '670 mm', velocity: '~370 m/s', range: '200 m', modes: ['semi', 'burst', 'auto'], ammo: 'pistol',
    overview: 'A modern polymer SMG with a very high rate of fire, ambidextrous controls and a folding stock.',
    how: ['Blowback from a closed bolt.', 'Polymer receiver with full-length rail.', 'Selector for single, 3-round burst and automatic.', 'Translucent magazines.'],
    history: 'Introduced in 2009 and adopted by police and military units in Europe and beyond.',
    feel: { recoil: 2, loud: 6, text: 'A buzzing, blistering burst at over 1,100 rpm.' },
    sound: { ...P.smg9, mech: 'bolt-closed' }, mv: 370, eff: 200, max: 1800, bulletG: 8, moa: '3–4 MOA', heat: 3, heatNote: 'High rate heats the barrel quickly.', env: [3, 4, 4, 3, 4], users: ['police', 'sf', 'army'], cart: '9x19',
    art: A.smg({ stock: { style: 'skeleton', x0: 0, x1: 200, top: -14, bot: 50, mat: 'poly' }, rec: { rail: [210, 460] }, mag: { mat: 'clear', curve: 22 }, fore: { style: 'mlok', x0: 470, x1: 580, top: -18, bot: 16, mat: 'poly' }, barrel: { x1: 640 }, muzzle: { style: 'comp', len: 20, r: 8 }, fsight: null, rsight: null, optic: { style: 'reddot', x0: 260, y: -22 } }) }),
  W({ id: 'awm', name: 'Accuracy International AWM', nickname: 'L115A3 (UK)', type: 'sniper', country: 'United Kingdom', year: 1996, designer: 'Accuracy International',
    wars: ['War in Afghanistan'], caliber: '.338 Lapua Magnum', action: 'Bolt action', capacity: 5, rpm: null, weight: '6.9 kg', length: '1,230 mm', velocity: '936 m/s', range: '1,500 m',
    modes: ['bolt'], ammo: 'rifle',
    overview: 'A world-class long-range sniper rifle. As the British L115A3 it made one of the longest recorded combat shots — 2,475 m in Afghanistan, 2009.',
    how: ['A strong bolt action with a 60° bolt throw.', 'The action is bonded to an aluminium chassis for consistency.', 'Folding stock, adjustable cheek-piece and bipod.', '.338 Lapua Magnum stays supersonic far beyond 1 km.'],
    history: 'Introduced in 1996; the British Army adopted the L115A3 version in 2008.',
    feel: { recoil: 7, loud: 10, text: 'A deep, powerful boom; the brake and weight keep you on the scope.' },
    sound: { ...P.full, power: 0.9, thump: 70, decay: 0.3, mech: 'bolt' }, mv: 936, eff: 1500, max: 5000, bulletG: 16.2, moa: '< 1 MOA', heat: 1, heatNote: 'Precision bolt action — heat is not a concern.', env: [4, 5, 4, 3, 5], users: ['army', 'sf'], cart: '338lm',
    art: A.boltSniper({ barrel: { x1: 1100 }, muzzle: { style: 'brake', len: 50, r: 10 } }) }),
  W({ id: 'fnmag', name: 'FN MAG', nickname: 'M240 (USA) · MAG 58', type: 'mg', country: 'Belgium', year: 1958, designer: 'Ernest Vervier (FN)', eras: ['cold', 'modern'],
    wars: ['Falklands War', 'Gulf War', 'Iraq War', 'Indian Army service (licensed MAG)'], caliber: '7.62×51mm NATO', action: 'Gas-operated, open bolt, tilting breechblock', capacity: 100,
    rpm: 750, weight: '11.8 kg', length: '1,263 mm', velocity: '840 m/s', range: '800 m (1,800 m tripod)', modes: ['auto'], ammo: 'belt',
    overview: 'One of the most widely used general-purpose machine guns in the world — over 80 countries, including India (licence-built) and the US (M240).',
    how: ['Gas piston drives a breechblock that tilts down to lock, like the BAR.', 'Fires from an open bolt to prevent cook-offs.', 'Adjustable gas regulator for rate of fire.', 'Quick-change barrel.'],
    history: 'Developed by FN in the 1950s and adopted widely in the 1960s; the US adopted it as the M240 in the 1970s.',
    feel: { recoil: 6, loud: 10, text: 'A heavy, rhythmic hammering — extremely reliable and steady.' },
    sound: { ...P.full, mech: 'gas', decay: 0.17 }, mv: 840, eff: 800, max: 3725, bulletG: 9.5, moa: '3–4 MOA (bipod)', heat: 4, heatNote: 'Barrel change every ~10 minutes of sustained fire.', env: [4, 4, 4, 4, 4], users: ['army', 'navy', 'airforce'], cart: '762x51',
    art: A.gpmg({ stock: { mat: 'wooddark' }, rec: { mat: 'blued' }, barrel: { mat: 'blued' }, fore: null, gasTube: { x0: 560, x1: 860, h: 9 } }) }),
  W({ id: 'l85', name: 'L85A2 (SA80)', type: 'rifle', country: 'United Kingdom', year: 1985, designer: 'RSAF Enfield', eras: ['cold', 'modern'],
    wars: ['Gulf War', 'Iraq War', 'War in Afghanistan'], caliber: '5.56×45mm NATO', action: 'Short-stroke gas piston, rotating bolt, bullpup', capacity: 30, rpm: 700,
    weight: '4.9 kg (with SUSAT)', length: '785 mm', velocity: '940 m/s', range: '400 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'The British Army\'s bullpup. The original L85A1 was notoriously unreliable; Heckler & Koch\'s 2002 rebuild (A2) turned it into a dependable and very accurate rifle.',
    how: ['Bullpup layout with the magazine behind the grip.', 'Short-stroke piston, rotating bolt.', 'Usually fitted with the SUSAT or ACOG magnified optic.', 'Right-handed only — cases eject past the face.'],
    history: 'Adopted in 1985; the A2 upgrade by H&K fixed most problems and the later A3 is still in service.',
    feel: { recoil: 3, loud: 8, text: 'Heavy rifle, mild recoil and a sharp crack beside your cheek.' },
    sound: P.r556, mv: 940, eff: 400, max: 3600, bulletG: 4, moa: '1.5–2.5 MOA', heat: 3, heatNote: 'Typical 5.56 heat; no quick-change barrel.', env: [3, 3, 3, 3, 3], users: ['army', 'navy', 'airforce'], cart: '556x45',
    envNote: 'Ratings are for the A2; the original A1 was unreliable in sand and cold.',
    art: A.bullpup({ optic: { style: 'scope', x0: 230, x1: 430, y: -48, r: 9, eb: 13, ob: 16, base: -26, rings: [270, 360] } }) }),
  W({ id: 'luger', name: 'Luger P08', nickname: 'Parabellum-Pistole', type: 'pistol', country: 'Germany', year: 1908, designer: 'Georg Luger', eras: ['ww1', 'ww2'],
    wars: ['World War I', 'World War II'], caliber: '9×19mm Parabellum', action: 'Short recoil, toggle lock', capacity: 8, rpm: null,
    weight: '0.87 kg', length: '222 mm', velocity: '350 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'The elegant toggle-locked German pistol — and the gun for which the 9×19mm Parabellum, the world\'s most popular pistol round, was created.',
    how: ['A jointed "toggle" on top locks the breech like a human knee.', 'On firing, the toggle hits a ramp and folds upward to unlock.', 'Raked grip angle makes it point naturally.', 'Precisely machined — but sensitive to dirt.'],
    history: 'Adopted by the German Navy (1904) and Army (1908). A prized war souvenir in both World Wars.',
    feel: { recoil: 4, loud: 6, text: 'Light, quick recoil; the toggle snaps up and back with every shot.' },
    sound: { ...P.pistol9, mech: 'roller' }, mv: 350, eff: 50, max: 1800, bulletG: 8, moa: '3–4 MOA', heat: 1, heatNote: 'Sidearm — no heat concerns.', env: [3, 3, 3, 2, 3], users: ['army', 'navy'], cart: '9x19',
    art: A.pistol({ barrelOut: 100, slide: { x0: 0, x1: 190, top: -22, bot: 4, mat: 'blued', serr: 0, port: [40, 70] }, frame: { x0: 0, x1: 200, top: 4, bot: 24, mat: 'blued', guardX: 150 }, grip: { x0: 10, x1: 76, y: 22, len: 120, ang: 28, mat: 'wood', panel: 'wood' }, magBase: 'blued', eject: { x: 80, y: -22 } }) }),
  W({ id: 'sten', name: 'Sten Mk II', type: 'smg', country: 'United Kingdom', year: 1941, designer: 'Shepherd & Turpin (Enfield)', eras: ['ww2'],
    wars: ['World War II', 'Indo-Pakistani War 1947', 'Arab–Israeli War 1948'], caliber: '9×19mm Parabellum', action: 'Straight blowback, open bolt', capacity: 32, rpm: 550,
    weight: '3.2 kg', length: '760 mm', velocity: '365 m/s', range: '100 m', modes: ['semi', 'auto'], ammo: 'pistol',
    overview: 'Britain\'s crude but effective emergency SMG — around four million were made, many in small workshops, and dropped to resistance fighters across Europe.',
    how: ['Simple open-bolt blowback with very few parts.', 'The magazine feeds from the left side, horizontally.', 'A tube receiver and skeleton stock made from stamped steel.', 'Selector for single shots or automatic.'],
    history: 'Designed in 1941 after Dunkirk, it cost a fraction of a Thompson. It was also used by Indian forces in 1947–48.',
    feel: { recoil: 3, loud: 6, text: 'A rattling, steady chatter; feels light and tinny.' },
    sound: P.smg9, mv: 365, eff: 100, max: 1800, bulletG: 8, moa: '5–8 MOA', heat: 3, heatNote: 'Open bolt helps cooling; no barrel change.', env: [3, 3, 3, 3, 3], users: ['army'], cart: '9x19',
    art: { kind: 'long', stock: { style: 'wire', x0: 0, x1: 180, top: -10, bot: 56, mat: 'blued' },
      rec: { x0: 180, x1: 520, top: -14, bot: 14, mat: 'blued', r: 13, port: [320, -10, 40, 10] }, grip: { x: 320, len: 50, ang: 0, w: 40, mat: 'blued' }, guard: { x: 330, w: 36, d: 18 },
      fore: { style: 'jacket', x0: 470, x1: 560, top: -14, bot: 14, mat: 'blued', hole: 14 }, barrel: { x0: 520, x1: 620, r: 7 }, muzzle: { style: 'none' }, fsight: { x: 600, h: 18 },
      bolt: { style: 'tab', x: 260, y: -22, w: 12, h: 10 }, eject: { x: 330, y: -10 }, extras: [['rect', 380, -12, 40, 24, 'dark', 3]] } }),
  W({ id: 'benelli', name: 'Benelli M4 (M1014)', type: 'shotgun', country: 'Italy', year: 1998, designer: 'Benelli Armi',
    wars: ['Iraq War', 'War in Afghanistan'], caliber: '12 gauge', action: 'Gas-operated (ARGO), rotating bolt, semi-auto', capacity: 7, rpm: null,
    weight: '3.8 kg', length: '1,010 mm', velocity: '~400 m/s (buckshot)', range: '40 m', modes: ['semi'], ammo: 'shell',
    overview: 'A semi-automatic combat shotgun adopted by the US Marine Corps as the M1014 — as fast as you can pull the trigger.',
    how: ['Twin self-cleaning gas pistons near the chamber (ARGO).', 'Rotating bolt; no pump to work.', 'Shells load into a tube under the barrel.', 'Collapsible stock and ghost-ring sights.'],
    history: 'Won the US Joint Service Combat Shotgun trials and entered service in 1999.',
    feel: { recoil: 8, loud: 9, text: 'Big 12-gauge blasts in quick succession; the gas system softens each kick.' },
    sound: { ...P.shotgun, mech: 'gas' }, mv: 400, eff: 40, max: 600, bulletG: 35, moa: '~2.5 cm spread per metre', heat: 2, heatNote: 'Tube capacity limits sustained fire.', env: [4, 4, 4, 4, 4], users: ['army', 'navy', 'police'], cart: '12ga',
    art: A.shotgun({ stock: { style: 'skeleton', x0: 0, x1: 300, top: -16, bot: 64, mat: 'poly' }, rec: { rail: [310, 460] } }) }),

  // ================================================================ USA
  W({ id: 'm14', name: 'M14', type: 'rifle', country: 'USA', year: 1959, designer: 'Springfield Armory', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Iraq War (as M14 EBR)', 'War in Afghanistan'], caliber: '7.62×51mm NATO', action: 'Gas-operated, rotating bolt', capacity: 20, rpm: 725,
    weight: '4.5 kg', length: '1,118 mm', velocity: '850 m/s', range: '460 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A Garand updated with a 20-round magazine and selective fire. Accurate and powerful, it lived on for decades as a marksman rifle.',
    how: ['Gas-driven operating rod rotates the bolt, like the M1 Garand.', '20-round detachable box magazine.', 'Wood (later fibreglass) stock.', 'Most were locked to semi-auto — full-auto 7.62 was hard to control.'],
    history: 'Adopted in 1959 and quickly replaced by the M16 in Vietnam, but brought back as a designated marksman rifle in Iraq and Afghanistan.',
    feel: { recoil: 8, loud: 9, text: 'A big, straight push and a booming report.' },
    sound: { ...P.full, mech: 'garand' }, mv: 850, eff: 460, max: 3725, bulletG: 9.5, moa: '1.5–3 MOA', heat: 4, heatNote: 'Automatic fire overheats it quickly.', env: [4, 4, 3, 3, 4], users: ['army', 'navy'], cart: '762x51',
    art: A.classic({ stock: { semiGrip: true, fore: 760, upper: [490, 740], bands: [740] }, rec: { x1: 490, mat: 'park' }, mag: { style: 'box', x: 410, w: 54, len: 70, y: 14 }, barrel: { x0: 490, x1: 940, mat: 'park' }, gasTube: { x0: 760, x1: 900, h: 7 }, muzzle: { style: 'flash', len: 28, r: 7 }, fsight: { x: 920, h: 24 }, rsight: { x: 340, h: 30, w: 30, y: -14 }, bolt: { style: 'tab', x: 460, y: -4, w: 26, h: 9 } }) }),
  W({ id: 'm2', name: 'M2 Browning', nickname: '"Ma Deuce"', type: 'mg', country: 'USA', year: 1933, designer: 'John Moses Browning', eras: ['ww2', 'cold', 'modern'],
    wars: ['World War II', 'Korean War', 'Vietnam War', 'Iraq War', 'War in Afghanistan'], caliber: '.50 BMG (12.7×99mm NATO)', action: 'Short recoil, open bolt', capacity: 100,
    rpm: 500, weight: '38 kg (gun only)', length: '1,654 mm', velocity: '890 m/s', range: '1,800 m', modes: ['semi', 'auto'], ammo: 'belt',
    overview: 'The legendary heavy machine gun, in service since the 1930s and still everywhere — on tanks, trucks, ships and tripods.',
    how: ['Short recoil: barrel and bolt recoil together before unlocking.', 'Fires from an open bolt; can be switched to single shots.', 'Heavy barrel inside a perforated jacket.', 'Spade grips with a thumb trigger on the back.'],
    history: 'Browning\'s WWI design, updated in 1933. Over 3 million have been built and it remains in production.',
    feel: { recoil: 9, loud: 10, text: 'A slow, earth-shaking "thud-thud-thud" — each round is a .50 BMG.' }, trivia: ['Its .50 BMG round was later adopted by the Barrett sniper rifles.'],
    sound: { power: 0.95, crack: 1, decay: 0.3, thump: 50, bright: 5200, tail: 1, mech: 'heavy' }, mv: 890, eff: 1800, max: 6800, bulletG: 42.8, moa: 'Area fire (tripod)', heat: 4, heatNote: 'Heavy barrel; barrel change during sustained fire.', env: [4, 4, 4, 4, 4], users: ['army', 'navy', 'airforce'], cart: '50bmg',
    art: { kind: 'long', rec: { x0: 160, x1: 560, top: -34, bot: 30, mat: 'park', r: 4 },
      mag: { style: 'belt', x: 380, len: 130, n: 9, sweep: 40 }, fore: { style: 'jacket', x0: 560, x1: 720, top: -20, bot: 20, mat: 'park', hole: 26 },
      barrel: { x0: 560, x1: 1120, r: 9, mat: 'park' }, muzzle: { style: 'cone', len: 36, r: 12 }, fsight: { x: 700, h: 30 }, rsight: { x: 500, h: 46, w: 16, y: -34 },
      bipod: { x: 360, len: 140, y: 30, splay: 50 }, eject: { x: 330, y: 30 }, ejectDown: true,
      extras: [['rect', 110, -30, 52, 60, 'park', 6], ['rect', 96, -40, 16, 26, 'rubber', 4], ['rect', 96, 14, 16, 26, 'rubber', 4]] } }),
  W({ id: 'm1carbine', name: 'M1 Carbine', type: 'rifle', country: 'USA', year: 1942, designer: 'Winchester (David M. Williams)', eras: ['ww2', 'cold'],
    wars: ['World War II', 'Korean War', 'Vietnam War'], caliber: '.30 Carbine', action: 'Gas-operated short-stroke piston, rotating bolt', capacity: 15, rpm: null,
    weight: '2.4 kg', length: '904 mm', velocity: '600 m/s', range: '300 m', modes: ['semi'], ammo: 'rifle',
    overview: 'A light, handy carbine for officers, paratroopers and support troops — more powerful than a pistol, lighter than a rifle. Over 6 million were made.',
    how: ['A tiny short-stroke piston taps the operating slide.', 'Rotating bolt, similar to the Garand.', '15-round box magazine.', 'Folding-stock M1A1 version for paratroopers.'],
    history: 'Adopted in 1942 and produced in greater numbers than any other US small arm of WWII.',
    feel: { recoil: 2, loud: 6, text: 'Light, gentle and quick — a sharp pop rather than a rifle boom.' },
    sound: { ...P.full, power: 0.5, decay: 0.13, thump: 120, bright: 7000, tail: 0.5, mech: 'garand' }, mv: 600, eff: 300, max: 2000, bulletG: 7.1, moa: '3–5 MOA', heat: 2, heatNote: 'Semi-auto fire keeps heat moderate.', env: [4, 4, 4, 3, 4], users: ['army', 'police'], cart: '30carb',
    art: A.classic({ stock: { wrist: 220, guard: 340, fore: 640, upper: [420, 620], bands: [600], semiGrip: false }, rec: { x0: 270, x1: 420, mat: 'park' }, mag: { style: 'box', x: 360, w: 40, len: 50, y: 14, mat: 'park' }, guard: { x: 350, y: 22, w: 56, d: 20 }, barrel: { x0: 420, x1: 760, mat: 'park' }, muzzle: { style: 'none' }, fsight: { x: 748, h: 20 }, rsight: { x: 300, h: 20, w: 20, y: -10 }, bolt: { style: 'tab', x: 400, y: -2, w: 18, h: 8 }, eject: { x: 330, y: -14 } }) }),
  W({ id: 'bar', name: 'M1918 BAR', nickname: 'Browning Automatic Rifle', type: 'lmg', country: 'USA', year: 1918, designer: 'John Moses Browning', eras: ['ww1', 'ww2', 'cold'],
    wars: ['World War I', 'World War II', 'Korean War'], caliber: '.30-06 Springfield', action: 'Gas-operated, tilting bolt, open bolt', capacity: 20, rpm: 500,
    weight: '8.8 kg', length: '1,214 mm', velocity: '860 m/s', range: '550 m', modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A "walking fire" automatic rifle that became the base of the US infantry squad in WWII.',
    how: ['Gas piston drives a bolt that tilts up to lock.', 'Fires from an open bolt.', '20-round box magazine — limited for an LMG.', 'Later A2 version added a bipod and slow/fast auto rates.'],
    history: 'Arrived in France in 1918. It was the firepower of every US rifle squad in WWII and Korea.',
    feel: { recoil: 5, loud: 9, text: 'Heavy and steady; a powerful, measured hammering of .30-06.' },
    sound: { ...P.full, mech: 'gas' }, mv: 860, eff: 550, max: 3500, bulletG: 9.7, moa: '3–5 MOA', heat: 4, heatNote: 'No quick-change barrel.', env: [4, 4, 4, 3, 4], users: ['army', 'navy'], cart: '3006',
    art: { kind: 'long', stock: { style: 'fixed', x0: 0, x1: 240, top: -2, bot: 72, mat: 'wood' }, rec: { x0: 240, x1: 560, top: -20, bot: 22, mat: 'park', r: 3 },
      guard: { x: 360, w: 56, d: 22 }, mag: { style: 'box', x: 420, w: 50, len: 80, mat: 'park' }, fore: { style: 'wood', x0: 560, x1: 720, top: -14, bot: 22, mat: 'wood' },
      barrel: { x0: 560, x1: 1000, r: 6, mat: 'park' }, muzzle: { style: 'cone', len: 34, r: 10 }, gasTube: { x0: 720, x1: 880, h: 8 }, fsight: { x: 990, h: 22 }, rsight: { x: 520, h: 30, w: 22, y: -20 },
      bipod: { x: 960, len: 100, y: 6, splay: 18 }, bolt: { style: 'tab', x: 500, y: 8, w: 22, h: 9 }, eject: { x: 450, y: -20 },
      extras: [['path', 'M290 20 L340 20 Q330 50 300 60 L270 56 Q290 40 290 20 Z', 'wood']] } }),
  W({ id: 'm24', name: 'M24 SWS', nickname: 'Sniper Weapon System', type: 'sniper', country: 'USA', year: 1988, designer: 'Remington Arms', eras: ['cold', 'modern'],
    wars: ['Gulf War', 'Iraq War', 'War in Afghanistan'], caliber: '7.62×51mm NATO', action: 'Bolt action (Remington 700)', capacity: 5, rpm: null,
    weight: '5.4 kg', length: '1,092 mm', velocity: '790 m/s', range: '800 m', modes: ['bolt'], ammo: 'rifle',
    overview: 'The US Army\'s standard sniper rifle for over 20 years, built on the famously accurate Remington 700 action.',
    how: ['A two-lug push-feed bolt action.', 'Heavy free-floating barrel in a fibreglass/Kevlar stock with an aluminium bedding block.', '5-round internal magazine.', 'Adjustable buttstock and Leupold optic.'],
    history: 'Adopted in 1988; replaced by the M2010 and semi-automatic M110 rifles.',
    feel: { recoil: 6, loud: 9, text: 'A firm, consistent shove and a sharp, cracking report.' },
    sound: { ...P.full, mech: 'bolt' }, mv: 790, eff: 800, max: 3725, bulletG: 11.3, moa: '~1 MOA', heat: 1, heatNote: 'Bolt action — heat is not a concern.', env: [4, 4, 4, 3, 4], users: ['army'], cart: '762x51',
    art: A.boltSniper({ stock: { style: 'fixed', x0: 0, x1: 300, top: -10, bot: 70, mat: 'olive', cheek: false }, mag: { style: 'internal', x: 430, w: 56, y: 14 }, muzzle: { style: 'none' }, barrel: { x1: 1000 } }) }),

  // ================================================================ ASIA-PACIFIC & ISRAEL
  W({ id: 'arisaka', name: 'Arisaka Type 99', type: 'rifle', country: 'Japan', year: 1939, designer: 'Imperial Japanese Army arsenals', eras: ['ww2'],
    wars: ['Second Sino-Japanese War', 'World War II — Pacific & Burma (incl. Imphal–Kohima, India 1944)'], caliber: '7.7×58mm Arisaka', action: 'Bolt action, front locking lugs', capacity: 5, rpm: null,
    weight: '3.8 kg', length: '1,118 mm', velocity: '730 m/s', range: '~500 m', modes: ['bolt'], ammo: 'rifle',
    overview: 'Japan\'s WWII service rifle — among the strongest bolt actions ever made. It was carried at the battles of Imphal and Kohima on India\'s north-east frontier in 1944.',
    how: ['Mauser-derived bolt with front locking lugs.', 'Five rounds loaded from stripper clips.', 'Early versions had a wire monopod and an anti-aircraft sight.', 'A sliding dust cover protected the action.'],
    history: 'Adopted in 1939 to replace the 6.5mm Type 38 with a more powerful 7.7mm round.',
    feel: { recoil: 7, loud: 8, text: 'A solid shove and a loud crack; smooth, strong bolt.' },
    sound: { ...P.full, mech: 'bolt' }, mv: 730, eff: 500, max: 3500, bulletG: 11.8, moa: '2–4 MOA', heat: 2, heatNote: 'Bolt action — heat is not a concern.', env: [4, 4, 4, 4, 4], users: ['army'], cart: '77x58',
    art: A.classic({ stock: { mat: 'wood', fore: 880, upper: [470, 860], bands: [600, 860] }, barrel: { x1: 930 }, fsight: { x: 918, h: 22 } }) }),
  W({ id: 'k2', name: 'Daewoo K2', type: 'rifle', country: 'South Korea', year: 1984, designer: 'Agency for Defense Development', eras: ['cold', 'modern'],
    wars: ['ROK Armed Forces service'], caliber: '5.56×45mm NATO', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30, rpm: 750,
    weight: '3.3 kg', length: '980 mm', velocity: '920 m/s', range: '600 m', modes: ['semi', 'burst', 'auto'], ammo: 'rifle',
    overview: 'South Korea\'s service rifle: an AR-style upper and lower combined with an AK-style long-stroke piston, plus a folding stock.',
    how: ['Long-stroke gas piston for reliability (AK principle).', 'AR-15-style controls and magazines.', 'Side-folding polymer stock.', 'Single, 3-round burst and automatic.'],
    history: 'Developed to give Korea an indigenous rifle, it entered service in 1984 and has been exported widely.',
    feel: { recoil: 3, loud: 8, text: 'Mild 5.56 recoil with a solid piston thump.' },
    sound: { ...P.r556, mech: 'ak' }, mv: 920, eff: 600, max: 3600, bulletG: 4, moa: '2–3 MOA', heat: 3, heatNote: 'Standard service-rifle heat limits.', env: [4, 4, 4, 4, 4], users: ['army', 'navy', 'airforce'], cart: '556x45',
    art: A.ar({ stock: { style: 'skeleton', x0: 0, x1: 250, top: -16, bot: 56, mat: 'poly' }, rec: { rail: null }, fore: { style: 'ribbed', x0: 480, x1: 680, top: -15, bot: 15, mat: 'poly' }, mag: { style: 'box', len: 100, ang: 4, mat: 'blued' }, fsight: { x: 700, h: 40 } }) }),
  W({ id: 'deagle', name: 'Desert Eagle .50 AE', type: 'pistol', country: 'Israel / USA', year: 1983, designer: 'Magnum Research · IMI', eras: ['cold', 'modern'],
    wars: ['Civilian, sport & film icon'], caliber: '.50 Action Express', action: 'Gas-operated, rotating bolt', capacity: 7, rpm: null,
    weight: '2.0 kg', length: '273 mm', velocity: '~470 m/s', range: '50 m', modes: ['semi'], ammo: 'pistol',
    overview: 'The famous hand-cannon. Unusually, it works like a rifle — a gas piston and rotating bolt — so it can handle magnum cartridges. Popular in films and games rather than with armed forces.',
    how: ['Gas taps from the barrel drive a piston under it.', 'A rifle-style rotating bolt locks into the barrel.', 'Fixed barrel with a top rail.', 'Massive slide and frame absorb recoil.'],
    history: 'Developed in the US and produced by Israel Military Industries from 1983; the .50 AE chambering arrived in 1991.',
    feel: { recoil: 9, loud: 9, text: 'A huge, deafening blast and a big upward flip — a lot of gun to hold.' },
    sound: { power: 0.72, crack: 0.5, decay: 0.18, thump: 85, bright: 5000, tail: 0.6, mech: 'gas' }, mv: 470, eff: 50, max: 2000, bulletG: 19.4, moa: '3–5 MOA', heat: 1, heatNote: '7 rounds — heat is never the issue; your wrist is.', env: [3, 4, 3, 2, 4], users: [], cart: '50ae',
    art: A.pistol({ hammer: true, slide: { x0: 0, x1: 330, top: -30, bot: 6, mat: 'steel', serr: 7, port: [110, 60] }, frame: { x0: 6, x1: 250, top: 6, bot: 30, mat: 'steel', guardX: 172 }, grip: { x0: 20, x1: 98, y: 26, len: 126, ang: 12, mat: 'poly', panel: 'poly' }, magBase: 'steel', eject: { x: 140, y: -30 } }) }),
];
