// Weapon database.
// sound: power 0-1 (energy), crack 0-1 (supersonic snap), decay s, thump Hz (body),
//        bright Hz (blast brightness), tail 0-1 (echo), mech: cycle sound type.
// feel:  1-10 subjective ratings used for the meters.

export const ERAS = [
  { id: 'all', label: 'All eras' },
  { id: 'ww1', label: 'World War I', years: '1914–18' },
  { id: 'ww2', label: 'World War II', years: '1939–45' },
  { id: 'cold', label: 'Cold War', years: '1947–91' },
  { id: 'modern', label: 'Modern', years: '1991–' },
];

export const TYPES = [
  { id: 'all', label: 'All' },
  { id: 'pistol', label: 'Pistols' },
  { id: 'smg', label: 'SMGs' },
  { id: 'rifle', label: 'Rifles' },
  { id: 'sniper', label: 'Snipers' },
  { id: 'mg', label: 'Machine guns' },
  { id: 'shotgun', label: 'Shotguns' },
];

export const MODE_LABELS = {
  semi: 'Single shot', burst: 'Burst', auto: 'Auto (hold)', bolt: 'Bolt action', pump: 'Pump action',
};

const P = {
  pistol45: { power: 0.45, crack: 0.15, decay: 0.13, thump: 105, bright: 4200, tail: 0.45, mech: 'slide' },
  pistol9: { power: 0.4, crack: 0.45, decay: 0.1, thump: 140, bright: 6200, tail: 0.4, mech: 'slide' },
  smg9: { power: 0.4, crack: 0.4, decay: 0.08, thump: 130, bright: 5800, tail: 0.35, mech: 'bolt-open' },
  smg45: { power: 0.44, crack: 0.12, decay: 0.09, thump: 100, bright: 4200, tail: 0.38, mech: 'bolt-open' },
  full: { power: 0.82, crack: 0.9, decay: 0.24, thump: 78, bright: 7000, tail: 0.75, mech: 'bolt' },
  inter: { power: 0.66, crack: 0.75, decay: 0.17, thump: 92, bright: 6500, tail: 0.6, mech: 'gas' },
  r556: { power: 0.6, crack: 0.95, decay: 0.14, thump: 118, bright: 8800, tail: 0.55, mech: 'gas' },
  mg: { power: 0.8, crack: 0.85, decay: 0.15, thump: 80, bright: 6800, tail: 0.65, mech: 'gas' },
  bmg: { power: 1, crack: 1, decay: 0.45, thump: 48, bright: 5200, tail: 1, mech: 'heavy' },
  shotgun: { power: 0.86, crack: 0.1, decay: 0.3, thump: 66, bright: 3400, tail: 0.8, mech: 'pump' },
};

export const WEAPONS = [
  // ---------------------------------------------------------------- PISTOLS
  {
    id: 'm1911', name: 'Colt M1911', nickname: 'The Government Model', type: 'pistol',
    country: 'USA', year: 1911, designer: 'John Moses Browning', eras: ['ww1', 'ww2', 'cold'],
    wars: ['World War I', 'World War II', 'Korean War', 'Vietnam War'],
    caliber: '.45 ACP (11.43×23mm)', action: 'Short recoil, tilting barrel (Browning link)', capacity: 7,
    rpm: null, weight: '1.1 kg', length: '216 mm', velocity: '253 m/s', range: '50 m',
    modes: ['semi'], ammo: 'pistol',
    overview: 'Standard US sidearm for 74 years. Built around the heavy, slow .45 ACP round after the US Army found the .38 revolver lacked stopping power in the Philippine–American War.',
    how: [
      'Hammer strikes the firing pin; the .45 ACP cartridge fires and the bullet travels down the barrel.',
      'Slide and barrel recoil backward together, locked by lugs, for a few millimetres.',
      'A swinging link tilts the barrel down and unlocks it; the slide keeps moving rearward alone.',
      'The extractor pulls the empty case out and the ejector flicks it from the port, cocking the hammer.',
      'The recoil spring drives the slide forward, stripping a fresh round from the 7-round magazine.',
    ],
    history: 'Adopted on 29 March 1911 after gruelling trials in which one test pistol fired 6,000 rounds without a malfunction. It served through both World Wars, Korea and Vietnam before the Beretta M9 replaced it in 1985 — and elite units kept using it for decades after.',
    feel: { recoil: 6, loud: 6, text: 'A heavy, rolling push rather than a sharp snap. The low muzzle velocity gives a deep, thudding "boom" without a supersonic crack.' },
    trivia: ['Over 2.7 million were made for the US military alone.', 'The grip safety was added at the request of the US Cavalry.'],
    sound: P.pistol45,
    art: { kind: 'pistol', hammer: true, beaver: true,
      slide: { x0: 0, x1: 300, top: -26, bot: 4, mat: 'park', serr: 9, port: [120, 46] },
      frame: { x0: 6, x1: 250, top: 4, bot: 26, mat: 'park', guardX: 150 },
      grip: { x0: 18, x1: 82, y: 22, len: 128, ang: 12, mat: 'wooddark', panel: 'wooddark' }, magBase: 'park',
      eject: { x: 140, y: -26 } },
  },
  {
    id: 'glock17', name: 'Glock 17', nickname: 'The Plastic Pistol', type: 'pistol',
    country: 'Austria', year: 1982, designer: 'Gaston Glock', eras: ['cold', 'modern'],
    wars: ['Iraq War', 'War in Afghanistan'],
    caliber: '9×19mm Parabellum', action: 'Short recoil, striker-fired, tilting barrel', capacity: 17,
    rpm: null, weight: '0.71 kg (empty)', length: '204 mm', velocity: '375 m/s', range: '50 m',
    modes: ['semi'], ammo: 'pistol',
    overview: 'A polymer-framed pistol designed by a curtain-rod manufacturer with no firearms experience. Simple, light and extremely reliable — today it is one of the most widely issued handguns on Earth.',
    how: [
      'Pulling the trigger finishes cocking the striker and releases it — no external hammer.',
      'Three passive safeties (trigger, firing pin, drop) disengage only while the trigger is pulled.',
      'Barrel and slide recoil together, then the barrel cams downward to unlock (Browning-style).',
      'The empty case is ejected to the right; the slide returns and chambers the next of 17 rounds.',
    ],
    history: 'Won the Austrian Army trials in 1982 as the P80. Early fears about a "plastic gun" that could slip through airport scanners proved to be myth — it contains plenty of steel. Adopted by the British Armed Forces in 2013.',
    feel: { recoil: 4, loud: 6, text: 'Snappy but light. The low bore axis keeps the muzzle from flipping much, giving a quick, sharp "crack".' },
    trivia: ['Has only around 34 parts.', 'Gen 5 models dropped the finger grooves on the grip.'],
    sound: P.pistol9,
    art: { kind: 'pistol',
      slide: { x0: 0, x1: 290, top: -28, bot: 4, mat: 'poly', serr: 8, port: [118, 48] },
      frame: { x0: 4, x1: 282, top: 4, bot: 26, mat: 'poly', guardX: 158 },
      grip: { x0: 10, x1: 86, y: 22, len: 120, ang: 20, mat: 'poly' }, magBase: 'poly',
      eject: { x: 140, y: -28 } },
  },
  // ---------------------------------------------------------------- BOLT ACTION RIFLES
  {
    id: 'smle', name: 'Lee–Enfield SMLE Mk III', nickname: 'The Smelly', type: 'rifle',
    country: 'United Kingdom', year: 1907, designer: 'James Paris Lee / RSAF Enfield', eras: ['ww1', 'ww2'],
    wars: ['World War I', 'World War II', 'Indo-Pakistani War 1947', 'Sino-Indian War 1962'],
    caliber: '.303 British (7.7×56mmR)', action: 'Bolt action, rear locking lugs, cock-on-closing', capacity: 10,
    rpm: null, weight: '3.96 kg', length: '1132 mm', velocity: '744 m/s', range: '503 m',
    modes: ['bolt'], ammo: 'rifle',
    overview: 'The fastest military bolt-action rifle of its day. A 10-round magazine and a short, smooth bolt throw let trained soldiers fire 20–30 aimed rounds a minute — the famous "Mad Minute".',
    how: [
      'Lift the bolt handle: rear-mounted lugs rotate out of the receiver, giving a short, fast stroke.',
      'Pull the bolt back to extract and eject the spent case.',
      'Push forward: a fresh round is stripped from the 10-round box magazine; the striker cocks on closing.',
      'Turn the handle down to lock — the rifle is ready to fire.',
    ],
    history: 'The British Army\'s standard rifle from 1907 well into WWII. In 1914 German troops reportedly believed they faced machine guns because of the rapid aimed fire of British regulars. India\'s Ishapore factory produced it for decades and it served Indian forces into the 1960s.',
    feel: { recoil: 7, loud: 8, text: 'A firm shove with a sharp, ringing "crack" and long echo, followed by the clack-clack of the bolt.' },
    trivia: ['Over 17 million Lee–Enfields of all types were made.', 'Still used by some police forces in South Asia.'],
    sound: { ...P.full, mech: 'bolt' },
    art: { kind: 'long',
      stock: { style: 'classic', x0: 0, top: 6, bot: 92, wrist: 260, guard: 400, fore: 920, mat: 'wood', upper: [470, 900], bands: [600, 880] },
      rec: { x0: 330, x1: 470, top: -14, bot: 10, mat: 'blued' },
      mag: { style: 'box', x: 420, w: 44, len: 50, y: 14, mat: 'blued' },
      guard: { x: 410, y: 22, w: 64, d: 22 },
      barrel: { x0: 470, x1: 960, r: 5 }, muzzle: { style: 'bayonetlug', len: 26 },
      fsight: { x: 948, h: 22 }, rsight: { x: 500, h: 14, w: 26, y: -4 },
      bolt: { style: 'knob', x: 360, drop: 18 }, eject: { x: 380, y: -14 } },
  },
  {
    id: 'kar98k', name: 'Mauser Karabiner 98k', nickname: 'K98k', type: 'rifle',
    country: 'Germany', year: 1935, designer: 'Mauser', eras: ['ww2'],
    wars: ['World War II', 'Spanish Civil War'],
    caliber: '7.92×57mm Mauser', action: 'Bolt action, controlled-feed, front locking lugs', capacity: 5,
    rpm: null, weight: '3.7–4.1 kg', length: '1110 mm', velocity: '760 m/s', range: '500 m (iron sights)',
    modes: ['bolt'], ammo: 'rifle',
    overview: 'The standard German infantry rifle of WWII. Its Mauser 98 action, with a big claw extractor that grips the cartridge from the magazine to ejection, is still the basis of many hunting rifles today.',
    how: [
      'Lift and pull the bolt; the claw extractor holds the case rim throughout the cycle (controlled feed).',
      'Push forward — the bolt strips a round from the internal 5-round magazine, loaded with stripper clips.',
      'Two large front lugs lock into the receiver ring for strength; a third safety lug sits at the rear.',
      'Pull the trigger to release the striker.',
    ],
    history: 'Over 14 million were produced between 1935 and 1945. Fitted with a scope it was the main German sniper rifle of the war. Post-war, it served many armies including Israel\'s early IDF.',
    feel: { recoil: 7, loud: 8, text: 'Hard-hitting 8mm round: a strong, straight push and a loud, sharp report.' },
    trivia: ['The "98" refers to the 1898 Mauser action it was based on.'],
    sound: { ...P.full, mech: 'bolt' },
    art: { kind: 'long',
      stock: { style: 'classic', x0: 0, top: 4, bot: 92, wrist: 255, guard: 400, fore: 860, mat: 'wooddark', semiGrip: true, upper: [470, 820], bands: [640, 840] },
      rec: { x0: 330, x1: 470, top: -14, bot: 10, mat: 'blued' },
      mag: { style: 'internal', x: 412, w: 60, y: 14, mat: 'blued' },
      guard: { x: 410, y: 22, w: 62, d: 22 },
      barrel: { x0: 470, x1: 920, r: 5 }, muzzle: { style: 'none' },
      fsight: { x: 905, h: 20 }, rsight: { x: 500, h: 14, w: 24, y: -4 },
      bolt: { style: 'straight', x: 345, drop: 24 }, eject: { x: 390, y: -14 } },
  },
  {
    id: 'mosin', name: 'Mosin–Nagant M91/30', nickname: 'Three-line rifle', type: 'rifle',
    country: 'Russia / USSR', year: 1891, designer: 'Sergei Mosin & Léon Nagant', eras: ['ww1', 'ww2'],
    wars: ['Russo-Japanese War', 'World War I', 'Winter War', 'World War II', 'Korean War'],
    caliber: '7.62×54mmR', action: 'Bolt action, front locking lugs', capacity: 5,
    rpm: null, weight: '4.0 kg', length: '1232 mm', velocity: '865 m/s', range: '500 m',
    modes: ['bolt'], ammo: 'rifle',
    overview: 'Rugged, simple and produced in vast numbers — the rifle of the Red Army. The 7.62×54mmR cartridge it introduced in 1891 is still in front-line use today in machine guns and the SVD.',
    how: [
      'Lift the bolt handle (a stiff motion — the bolt also cocks on opening).',
      'Draw back to extract; the case is ejected upward and to the right.',
      'Push forward to feed one of 5 rounds; an "interrupter" stops rimmed cartridges double-feeding.',
      'Turn down to lock the two front lugs.',
    ],
    history: 'Called the "three-line rifle" because its bore measured three lines (0.3 inch). Around 37 million were made. Finnish sniper Simo Häyhä used a Mosin variant with iron sights during the Winter War.',
    feel: { recoil: 8, loud: 9, text: 'A stout kick and a big, booming report with noticeable muzzle flash.' },
    trivia: ['It was usually zeroed with the bayonet fixed.'],
    sound: { ...P.full, power: 0.86, mech: 'bolt' },
    art: { kind: 'long',
      stock: { style: 'classic', x0: 0, top: 4, bot: 92, wrist: 250, guard: 395, fore: 930, mat: 'woodred', upper: [480, 890], bands: [650, 900] },
      rec: { x0: 330, x1: 480, top: -14, bot: 10, mat: 'blued' },
      mag: { style: 'internal', x: 405, w: 66, y: 14, mat: 'blued' },
      guard: { x: 405, y: 24, w: 66, d: 20 },
      barrel: { x0: 480, x1: 990, r: 5 }, muzzle: { style: 'none' },
      fsight: { x: 978, h: 20 }, rsight: { x: 500, h: 14, w: 30, y: -4 },
      bolt: { style: 'straight', x: 352, drop: 24 }, eject: { x: 390, y: -14 } },
  },
  // ---------------------------------------------------------------- WWII AUTO / SEMI
  {
    id: 'garand', name: 'M1 Garand', nickname: '"The greatest battle implement ever devised" — Gen. Patton', type: 'rifle',
    country: 'USA', year: 1936, designer: 'John C. Garand', eras: ['ww2', 'cold'],
    wars: ['World War II', 'Korean War', 'Vietnam War (early)'],
    caliber: '.30-06 Springfield (7.62×63mm)', action: 'Gas-operated, rotating bolt', capacity: 8,
    rpm: null, weight: '4.3 kg', length: '1100 mm', velocity: '853 m/s', range: '460 m',
    modes: ['semi'], ammo: 'rifle', ping: true,
    overview: 'The first semi-automatic rifle to become a nation\'s standard infantry weapon. While most WWII soldiers worked a bolt, Americans could fire as fast as they pulled the trigger.',
    how: [
      'Gas tapped near the muzzle pushes an operating rod back.',
      'The op-rod rotates and unlocks the bolt, extracts and ejects the case, and cocks the hammer.',
      'A spring returns everything forward, chambering the next round from the 8-round en-bloc clip.',
      'After the 8th shot the empty clip is ejected with its famous metallic "PING!"',
    ],
    history: 'Adopted in 1936, over 5.4 million were made. It gave US infantry a large firepower advantage in WWII and Korea. The "ping" of the ejected clip is one of the most recognisable sounds in military history.',
    feel: { recoil: 7, loud: 8, text: 'A long, heavy push of the full-power .30-06, softened a little by the gas system and the rifle\'s weight.' },
    trivia: ['The clip can only be loaded full — no topping off.', '"Garand thumb" is what happens if you let the bolt close on your thumb.'],
    sound: { ...P.full, mech: 'gas' },
    art: { kind: 'long',
      stock: { style: 'classic', x0: 0, top: 6, bot: 92, wrist: 260, guard: 400, fore: 760, mat: 'wood', semiGrip: true, upper: [500, 740], bands: [740] },
      rec: { x0: 330, x1: 500, top: -16, bot: 10, mat: 'park' },
      mag: { style: 'internal', x: 405, w: 70, y: 14, mat: 'park' },
      guard: { x: 410, y: 22, w: 64, d: 22 },
      barrel: { x0: 500, x1: 940, r: 5, mat: 'park' }, gasTube: { x0: 760, x1: 925, h: 7 },
      muzzle: { style: 'bayonetlug', len: 18, mat: 'park' },
      fsight: { x: 920, h: 24 }, rsight: { x: 340, h: 30, w: 30, y: -14 },
      bolt: { style: 'tab', x: 470, y: -4, w: 26, h: 9 }, eject: { x: 410, y: -16 } },
  },
  {
    id: 'thompson', name: 'Thompson M1928A1', nickname: 'Tommy Gun / Chicago Typewriter', type: 'smg',
    country: 'USA', year: 1928, designer: 'John T. Thompson', eras: ['ww2'],
    wars: ['World War II', 'Korean War', 'Chinese Civil War'],
    caliber: '.45 ACP', action: 'Delayed blowback (Blish lock), open bolt', capacity: 50,
    rpm: 700, weight: '4.9 kg', length: '852 mm', velocity: '285 m/s', range: '50 m',
    modes: ['semi', 'auto'], ammo: 'pistol',
    overview: 'The original "submachine gun" — Thompson coined the term. Infamous with Prohibition gangsters, then iconic with Allied troops in WWII.',
    how: [
      'The bolt is held open; pulling the trigger releases it to slam forward and fire the round.',
      'A sliding H-shaped Blish lock briefly delays the bolt\'s opening under pressure.',
      'The bolt flies back, ejecting the case, and repeats while the trigger is held.',
      'Fed by 20/30-round sticks or the iconic 50-round drum.',
    ],
    history: 'Designed to "sweep" trenches at the end of WWI, it arrived too late for that war. In the 1920s it became notorious as the "Chicago Typewriter". Britain bought huge numbers in 1940, and the simplified M1/M1A1 armed US troops throughout WWII.',
    feel: { recoil: 4, loud: 6, text: 'Heavy gun, soft push. A deep, chugging "thud-thud-thud" of subsonic .45 at around 700 rounds a minute.' },
    trivia: ['A drum-fed M1928 weighed over 6 kg loaded.', 'Winston Churchill was famously photographed holding one.'],
    sound: P.smg45,
    art: { kind: 'long',
      stock: { style: 'thompson', x0: 0, top: 4, bot: 80, mat: 'wood' },
      rec: { x0: 250, x1: 500, top: -20, bot: 18, mat: 'blued', r: 6 },
      grip: { x: 330, len: 70, ang: 10, w: 32, mat: 'wood' },
      guard: { x: 360, w: 50, d: 22 },
      mag: { style: 'drum', x: 410, w: 50, r: 62, y: 14, mat: 'blued' },
      vgrip: { x: 600, len: 70, y: 12, mat: 'wood' },
      fore: { style: 'plain', x0: 500, x1: 560, top: -14, bot: 14, mat: 'blued' },
      barrel: { x0: 500, x1: 760, r: 7 }, muzzle: { style: 'cutts', len: 38, r: 9 },
      fsight: { x: 770, h: 16 }, rsight: { x: 280, h: 30, w: 24, y: -18 },
      bolt: { style: 'tab', x: 430, y: -28, w: 16, h: 10 }, eject: { x: 420, y: -18 },
      extras: [['rect', 518, 12, 60, 12, 'blued', 3]] },
  },
  {
    id: 'mp40', name: 'MP 40', nickname: 'Schmeisser', type: 'smg',
    country: 'Germany', year: 1940, designer: 'Heinrich Vollmer / Erma Werke', eras: ['ww2'],
    wars: ['World War II'],
    caliber: '9×19mm Parabellum', action: 'Straight blowback, open bolt', capacity: 32,
    rpm: 550, weight: '4.0 kg', length: '833 mm (stock extended)', velocity: '400 m/s', range: '100 m',
    modes: ['auto'], ammo: 'pistol',
    overview: 'One of the first guns built from stamped steel and plastic rather than machined wood and metal — a template for mass-produced modern weapons.',
    how: [
      'An open bolt: the heavy bolt is held back until the trigger is pulled.',
      'The bolt flies forward, chambers a round and fires it in one motion.',
      'Pressure blows the bolt back against a telescoping recoil spring; no locking mechanism.',
      'No selector — trained users fired single shots with quick trigger taps. The slow 550 rpm made that possible.',
    ],
    history: 'Around 1.1 million were produced. Allied troops often (wrongly) called it the "Schmeisser". A hook under the barrel let it be fired steadily from armoured vehicle firing ports.',
    feel: { recoil: 3, loud: 6, text: 'Very controllable. A steady, rhythmic "brrrap" — slow enough to hear each individual shot.' },
    trivia: ['Its Bakelite lower receiver was one of the first uses of plastic in a firearm.'],
    sound: P.smg9,
    art: { kind: 'long',
      stock: { style: 'wire', x0: 0, x1: 210, top: -8, bot: 70, mat: 'blued' },
      rec: { x0: 210, x1: 470, top: -18, bot: 16, mat: 'blued', r: 8, lower: 'M250 16 L420 16 L420 34 L250 34 Z', lowerMat: 'poly' },
      grip: { x: 300, len: 72, ang: 10, w: 34, mat: 'poly' },
      guard: { x: 330, y: 34, w: 50, d: 20 },
      mag: { style: 'box', x: 420, w: 36, len: 170, y: 14, mat: 'blued' },
      fore: { style: 'plain', x0: 470, x1: 520, top: -14, bot: 14, mat: 'blued' },
      barrel: { x0: 470, x1: 690, r: 7 }, muzzle: { style: 'comp', len: 18, r: 9 },
      fsight: { x: 680, h: 20 }, rsight: { x: 250, h: 30, w: 16, y: -18 },
      bolt: { style: 'tab', x: 330, y: -26, w: 12, h: 10 }, eject: { x: 380, y: -18 },
      extras: [['rect', 540, 6, 40, 14, 'blued', 2]] },
  },
  {
    id: 'ppsh41', name: 'PPSh-41', nickname: 'Papasha ("Daddy")', type: 'smg',
    country: 'USSR', year: 1941, designer: 'Georgy Shpagin', eras: ['ww2', 'cold'],
    wars: ['World War II', 'Korean War', 'Vietnam War'],
    caliber: '7.62×25mm Tokarev', action: 'Straight blowback, open bolt', capacity: 71,
    rpm: 1000, weight: '3.6 kg', length: '843 mm', velocity: '488 m/s', range: '150 m',
    modes: ['semi', 'auto'], ammo: 'pistol',
    overview: 'Cheap, crude and astonishingly fast-firing. Some six million were stamped out, arming entire Soviet units with submachine guns.',
    how: [
      'Open-bolt blowback, like the MP 40 — but with a lighter bolt, giving ~1,000 rounds per minute.',
      'The angled front of the barrel shroud acts as a muzzle brake, fighting muzzle climb.',
      'Fed from a 71-round drum, later a simpler 35-round box.',
    ],
    history: 'Designed for mass production by unskilled labour in 1941. Germans prized captured examples, converting some to 9mm. In Korea, UN troops nicknamed it the "burp gun" for its sound.',
    feel: { recoil: 3, loud: 7, text: 'A blistering, high-pitched "BRRRRT" — individual shots blur together. Muzzle rise is surprisingly low.' },
    trivia: ['A full drum could be emptied in about 5 seconds.'],
    sound: { ...P.smg9, crack: 0.6, bright: 7200 },
    art: { kind: 'long',
      stock: { style: 'thompson', x0: 0, top: 6, bot: 82, mat: 'woodred' },
      rec: { x0: 250, x1: 450, top: -20, bot: 16, mat: 'blued', r: 6 },
      guard: { x: 330, y: 30, w: 60, d: 20 },
      mag: { style: 'drum', x: 370, w: 50, r: 64, y: 14, mat: 'blued' },
      fore: { style: 'jacket', x0: 450, x1: 700, top: -16, bot: 16, mat: 'blued', hole: 22 },
      barrel: { x0: 450, x1: 705, r: 6 }, muzzle: { style: 'comp', len: 26, r: 16 },
      fsight: { x: 700, h: 24 }, rsight: { x: 270, h: 28, w: 18, y: -18 },
      bolt: { style: 'tab', x: 400, y: -26, w: 14, h: 10 }, eject: { x: 380, y: -20 },
      extras: [['path', 'M250 16 L330 16 Q320 60 290 70 L240 70 Q260 40 250 16 Z', 'woodred']] },
  },
  {
    id: 'mg42', name: 'MG 42', nickname: '"Hitler\'s Buzzsaw"', type: 'mg',
    country: 'Germany', year: 1942, designer: 'Werner Gruner', eras: ['ww2'],
    wars: ['World War II'],
    caliber: '7.92×57mm Mauser', action: 'Recoil-operated, roller-locked', capacity: 250,
    rpm: 1200, weight: '11.6 kg', length: '1220 mm', velocity: '740 m/s', range: '200–2000 m',
    modes: ['auto'], ammo: 'belt',
    overview: 'A general-purpose machine gun with a terrifying rate of fire — so fast the ear cannot pick out individual shots, producing a tearing-cloth sound.',
    how: [
      'Two rollers in the bolt head lock it into the barrel extension at the moment of firing.',
      'Recoil pushes barrel and bolt back together; cams force the rollers inward, unlocking the bolt.',
      'A muzzle booster uses gas to add extra recoil, driving the cycle to ~1,200 rounds/min.',
      'The barrel overheats fast — crews swapped it in seconds through the side of the jacket.',
    ],
    history: 'Built largely from stamped steel to speed production. Its successor, the MG3, is still in service with many armies today. Allied soldiers were trained to treat its sound as a psychological weapon.',
    feel: { recoil: 6, loud: 10, text: 'A continuous ripping roar ("buzzsaw") with heavy vibration — it walks off target without a firm bipod.' },
    trivia: ['A 50-round belt lasted under 3 seconds.'],
    sound: { ...P.mg, decay: 0.12 },
    art: { kind: 'long',
      stock: { style: 'mg', x0: 0, x1: 190, top: -10, bot: 70, mat: 'poly' },
      rec: { x0: 190, x1: 470, top: -24, bot: 18, mat: 'blued', r: 3 },
      grip: { x: 270, len: 70, ang: 8, w: 32, mat: 'poly' },
      guard: { x: 300, w: 54, d: 22 },
      mag: { style: 'belt', x: 400, len: 140, n: 10, sweep: 40 },
      fore: { style: 'jacket', x0: 470, x1: 880, top: -20, bot: 20, mat: 'blued', hole: 30 },
      barrel: { x0: 470, x1: 900, r: 6 }, muzzle: { style: 'cone', len: 40, r: 14 },
      fsight: { x: 860, h: 34 }, rsight: { x: 470, h: 34, w: 18, y: -20 },
      bipod: { x: 840, len: 110, y: 18, splay: 22 }, eject: { x: 360, y: 18 } },
  },
  // ---------------------------------------------------------------- COLD WAR
  {
    id: 'ak47', name: 'AK-47', nickname: 'Avtomat Kalashnikova', type: 'rifle',
    country: 'USSR', year: 1949, designer: 'Mikhail Kalashnikov', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Soviet–Afghan War', 'Iran–Iraq War', 'countless others'],
    caliber: '7.62×39mm', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30,
    rpm: 600, weight: '3.47 kg', length: '880 mm', velocity: '715 m/s', range: '350 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'The most produced firearm in history — estimates exceed 75 million AK-pattern rifles. Loose tolerances and a massive piston let it keep working in mud, sand and ice.',
    how: [
      'Gas from a port near the muzzle drives a long piston, permanently attached to the bolt carrier.',
      'The carrier travels back, rotating the bolt via a cam to unlock it, then extracts and ejects.',
      'A return spring slams the carrier home, feeding a round from the curved 30-round magazine.',
      'The selector reads Safe → Auto → Semi (top to bottom).',
    ],
    history: 'Adopted by the Soviet Army in 1949 and copied or licensed by dozens of countries. It appears on the flag of Mozambique. The intermediate 7.62×39 cartridge made controllable automatic fire practical for every soldier.',
    feel: { recoil: 6, loud: 8, text: 'A heavy, chunky push with a distinctive harsh "crack-thump" and a loud clatter from the reciprocating carrier.' },
    trivia: ['The curved magazine is due to the tapered 7.62×39 case.', 'Kalashnikov said he wished he\'d invented a lawnmower instead.'],
    sound: P.inter,
    art: { kind: 'long',
      stock: { style: 'ak', x0: 0, x1: 240, top: 4, bot: 74, mat: 'wood' },
      rec: { x0: 240, x1: 560, top: -18, bot: 20, mat: 'blued', r: 2, port: [430, -10, 60, 10], lines: [[290, -18, 560, -18]] },
      grip: { x: 310, len: 76, ang: 16, w: 30, mat: 'wood' },
      guard: { x: 360, w: 54, d: 22 },
      mag: { style: 'curved', x: 400, w: 44, len: 150, curve: 70, mat: 'blued' },
      fore: { style: 'ak', x0: 560, x1: 720, top: -8, bot: 16, mat: 'wood', ut: -28, ux: 700 },
      gasTube: { x0: 700, x1: 790, h: 9 },
      barrel: { x0: 560, x1: 930, r: 5 }, muzzle: { style: 'ak', len: 26, r: 7 },
      fsight: { x: 905, h: 30 }, rsight: { x: 548, h: 26, w: 26, y: -16 },
      bolt: { style: 'tab', x: 500, y: -10, w: 26, h: 9 }, eject: { x: 460, y: -18 } },
  },
  {
    id: 'm16a1', name: 'M16A1', nickname: 'The Black Rifle', type: 'rifle',
    country: 'USA', year: 1967, designer: 'Eugene Stoner (ArmaLite)', eras: ['cold'],
    wars: ['Vietnam War', 'Grenada', 'Panama'],
    caliber: '5.56×45mm NATO', action: 'Direct impingement gas, rotating bolt', capacity: 20,
    rpm: 750, weight: '2.9 kg', length: '986 mm', velocity: '960 m/s', range: '460 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A space-age rifle of aluminium and plastic firing a small, very fast 5.56mm bullet. Light enough that a soldier could carry twice the ammunition of the M14.',
    how: [
      'No piston: hot gas is piped through a thin tube straight into the bolt carrier ("direct impingement").',
      'Gas expands inside the carrier, pushing it back and rotating the 7-lug bolt to unlock.',
      'The carrier and buffer move into the stock tube; the buffer spring returns them.',
      'Its in-line stock directs recoil straight back, keeping the muzzle low.',
    ],
    history: 'Early M16s in Vietnam suffered jams due to powder changes and a lack of cleaning kits. The A1 added a chrome-plated chamber, a forward assist and cleaning kits — and became the US standard rifle for decades.',
    feel: { recoil: 3, loud: 8, text: 'Light, quick recoil; a sharp, high "crack" and a springy "sproing" from the buffer.' },
    trivia: ['The 20-round magazine was usually loaded with 18 to avoid feed problems.'],
    sound: P.r556,
    art: { kind: 'long',
      stock: { style: 'fixed', x0: 0, x1: 260, top: -14, bot: 62, mat: 'poly' },
      rec: { x0: 260, x1: 520, top: -24, bot: 18, mat: 'poly', r: 3, port: [400, -12, 50, 12],
        lower: 'M290 18 L470 18 L470 36 L290 36 Z', lowerMat: 'poly' },
      grip: { x: 340, len: 76, ang: 20, w: 30, mat: 'poly' },
      guard: { x: 390, y: 36, w: 54, d: 20 },
      mag: { style: 'box', x: 420, w: 44, len: 100, ang: 4, y: 32, mat: 'blued' },
      fore: { style: 'ribbed', x0: 520, x1: 730, top: -15, bot: 15, mat: 'poly' },
      barrel: { x0: 520, x1: 950, r: 5 }, muzzle: { style: 'flash', len: 36, r: 7 },
      fsight: { x: 770, h: 46 },
      optic: { style: 'carry', x0: 290, x1: 470, y: -24 },
      bolt: { style: 'tab', x: 270, y: -32, w: 22, h: 8 }, eject: { x: 425, y: -12 } },
  },
  {
    id: 'fal', name: 'FN FAL', nickname: 'Right arm of the free world', type: 'rifle',
    country: 'Belgium', year: 1953, designer: 'Dieudonné Saive', eras: ['cold', 'modern'],
    wars: ['Falklands War (both sides)', 'Six-Day War', 'Indo-Pakistani War 1971 (Indian 1A SLR)', 'Kargil War'],
    caliber: '7.62×51mm NATO', action: 'Gas-operated short-stroke piston, tilting breechblock', capacity: 20,
    rpm: 650, weight: '4.3 kg', length: '1090 mm', velocity: '840 m/s', range: '600 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'Used by over 90 countries during the Cold War. India manufactured the semi-automatic 1A/1A1 Self-Loading Rifle (SLR) version for decades.',
    how: [
      'Gas taps a short piston that strikes the bolt carrier and then stops.',
      'The carrier lifts the rear of the breechblock out of a locking shoulder ("tilting block").',
      'An adjustable gas regulator lets the soldier tune it for dirt or weather.',
      'Full-power 7.62 NATO in automatic is hard to control — most armies issued semi-only versions.',
    ],
    history: 'Originally designed for the German 7.92 Kurz intermediate round, then rebuilt for 7.62 NATO. In the 1982 Falklands War both British (L1A1) and Argentine (FAL) troops carried it.',
    feel: { recoil: 8, loud: 9, text: 'A powerful, booming shot with a stout, straight shove. Full-auto is a wild ride.' },
    trivia: ['The Indian SLR remained in service until the INSAS replaced it in the late 1990s.'],
    sound: { ...P.full, mech: 'gas' },
    art: { kind: 'long',
      stock: { style: 'fixed', x0: 0, x1: 250, top: -4, bot: 70, mat: 'wooddark' },
      rec: { x0: 250, x1: 540, top: -22, bot: 18, mat: 'blued', r: 3, port: [410, -12, 60, 12] },
      grip: { x: 330, len: 76, ang: 16, w: 30, mat: 'poly' },
      guard: { x: 375, w: 54, d: 22 },
      mag: { style: 'box', x: 420, w: 50, len: 100, ang: 6, mat: 'blued' },
      fore: { style: 'wood', x0: 540, x1: 740, top: -16, bot: 18, mat: 'wooddark' },
      barrel: { x0: 540, x1: 950, r: 5 }, muzzle: { style: 'flash', len: 40, r: 8 },
      gasTube: { x0: 740, x1: 800, h: 8 },
      fsight: { x: 790, h: 34 }, rsight: { x: 500, h: 34, w: 24, y: -22 },
      bolt: { style: 'tab', x: 520, y: -14, w: 20, h: 9 }, eject: { x: 440, y: -12 },
      extras: [['rect', 300, -36, 20, 14, 'blued', 2]] },
  },
  {
    id: 'uzi', name: 'Uzi', nickname: '', type: 'smg',
    country: 'Israel', year: 1954, designer: 'Uziel Gal', eras: ['cold', 'modern'],
    wars: ['Suez Crisis', 'Six-Day War', 'Yom Kippur War'],
    caliber: '9×19mm Parabellum', action: 'Straight blowback, open bolt, telescoping bolt', capacity: 32,
    rpm: 600, weight: '3.5 kg', length: '650 mm (stock extended)', velocity: '400 m/s', range: '100 m',
    modes: ['semi', 'auto'], ammo: 'pistol',
    overview: 'Compact and famously easy to reload in the dark — "hand finds hand" — because the magazine goes into the pistol grip.',
    how: [
      'The bolt wraps around the rear of the barrel (telescoping), letting a long barrel fit in a short gun.',
      'Open bolt blowback: the bolt slams forward to fire when the trigger releases it.',
      'A grip safety must be squeezed or the bolt cannot move.',
      'Magazine housed inside the pistol grip balances the gun over the hand.',
    ],
    history: 'Adopted by the IDF in 1954 and exported to over 90 countries. Famous as a US Secret Service weapon — an agent drew one during the 1981 Reagan assassination attempt.',
    feel: { recoil: 3, loud: 6, text: 'Compact and chunky; a steady, controllable stutter with a bark from the short barrel.' },
    trivia: ['Uziel Gal didn\'t want it named after himself — he was overruled.'],
    sound: P.smg9,
    art: { kind: 'long',
      stock: { style: 'wire', x0: 0, x1: 180, top: -10, bot: 60, mat: 'blued' },
      rec: { x0: 180, x1: 480, top: -22, bot: 20, mat: 'park', r: 4, port: [330, -14, 50, 14],
        lower: 'M220 20 L440 20 L440 34 L220 34 Z', lowerMat: 'poly' },
      grip: { x: 330, len: 110, ang: 6, w: 44, mat: 'poly' },
      guard: { x: 410, y: 34, w: 60, d: 20 },
      mag: { style: 'gripmag', x: 274, w: 44, y: 104, mat: 'blued' },
      barrel: { x0: 480, x1: 540, r: 8 }, muzzle: { style: 'none' },
      fsight: { x: 470, h: 36 }, rsight: { x: 190, h: 36, w: 14, y: -22 },
      bolt: { style: 'tab', x: 240, y: -32, w: 18, h: 10 }, eject: { x: 350, y: -18 } },
  },
  {
    id: 'm60', name: 'M60', nickname: 'The Pig', type: 'mg',
    country: 'USA', year: 1957, designer: 'Springfield Armory / Saco', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Gulf War', 'Iraq War'],
    caliber: '7.62×51mm NATO', action: 'Gas-operated, open bolt, rotating bolt', capacity: 100,
    rpm: 550, weight: '10.5 kg', length: '1105 mm', velocity: '853 m/s', range: '1100 m (tripod)',
    modes: ['auto'], ammo: 'belt',
    overview: 'The American general-purpose machine gun of the Vietnam era, carried by squad machine gunners and mounted on helicopters and vehicles.',
    how: [
      'Fires from an open bolt to prevent rounds "cooking off" in a hot chamber.',
      'Gas drives a piston and operating rod, rotating and unlocking the bolt.',
      'Belt-fed: a feed arm pulls a disintegrating-link belt across the tray each cycle.',
      'The barrel can be changed when hot — though early models fixed the bipod to it.',
    ],
    history: 'Influenced by the German MG 42 and FG 42 designs. Its bulk earned it the nickname "the Pig". Replaced in most US roles by the FN M240 from the 1990s.',
    feel: { recoil: 5, loud: 10, text: 'A slow, heavy, pounding rhythm — "chug-chug-chug" — at a controllable 550 rpm.' },
    trivia: ['Rambo carried one in "First Blood Part II".'],
    sound: { ...P.mg, decay: 0.18 },
    art: { kind: 'long',
      stock: { style: 'mg', x0: 0, x1: 210, top: -12, bot: 62, mat: 'poly' },
      rec: { x0: 210, x1: 520, top: -26, bot: 16, mat: 'park', r: 4 },
      grip: { x: 340, len: 70, ang: 12, w: 30, mat: 'poly' },
      guard: { x: 370, w: 52, d: 22 },
      mag: { style: 'belt', x: 440, len: 120, n: 9, sweep: 30 },
      fore: { style: 'plain', x0: 520, x1: 700, top: -18, bot: 22, mat: 'poly' },
      barrel: { x0: 520, x1: 960, r: 7, mat: 'park' }, muzzle: { style: 'flash', len: 34, r: 9 },
      gasTube: { x0: 700, x1: 830, h: 10 },
      fsight: { x: 920, h: 30 }, rsight: { x: 470, h: 40, w: 22, y: -26 },
      bipod: { x: 840, len: 110, y: 10, splay: 20 },
      eject: { x: 400, y: 16 },
      extras: [['rect', 560, -46, 60, 10, 'park', 4], ['rect', 580, -38, 8, 14, 'park', 1]] },
  },
  {
    id: 'mp5', name: 'Heckler & Koch MP5', nickname: '', type: 'smg',
    country: 'West Germany', year: 1966, designer: 'Heckler & Koch', eras: ['cold', 'modern'],
    wars: ['Iranian Embassy Siege (1980)', 'Gulf War', 'counter-terror operations'],
    caliber: '9×19mm Parabellum', action: 'Roller-delayed blowback, closed bolt', capacity: 30,
    rpm: 800, weight: '2.54 kg', length: '680 mm', velocity: '400 m/s', range: '200 m',
    modes: ['semi', 'burst', 'auto'], ammo: 'pistol',
    overview: 'The definitive counter-terror submachine gun. Firing from a closed bolt makes it far more accurate than earlier SMGs.',
    how: [
      'Two rollers in the bolt head must be cammed inward before the bolt can move back — delaying opening.',
      'Firing from a closed bolt: only the hammer moves when you pull the trigger, aiding accuracy.',
      'Fluted chamber lets gas "float" the case for easy extraction.',
      'The "Navy" trigger pack offers safe, single, 3-round burst and full-auto.',
    ],
    history: 'Derived from the G3 rifle. Became world-famous on 5 May 1980 when the British SAS stormed the Iranian Embassy in London live on TV. Used by special forces and police in 40+ countries.',
    feel: { recoil: 2, loud: 6, text: 'Smooth and soft-shooting; a crisp "tat-tat-tat" with very little muzzle rise.' },
    trivia: ['The "HK slap" — slapping the cocking lever down — is the signature reload.'],
    sound: { ...P.smg9, mech: 'bolt-closed' },
    art: { kind: 'long',
      stock: { style: 'fixed', x0: 0, x1: 200, top: -12, bot: 56, mat: 'poly', joinT: 4 },
      rec: { x0: 200, x1: 470, top: -22, bot: 14, mat: 'poly', r: 4, port: [330, -12, 44, 12],
        lower: 'M230 14 L400 14 L400 30 L230 30 Z', lowerMat: 'poly' },
      grip: { x: 290, len: 74, ang: 14, w: 30, mat: 'poly' },
      guard: { x: 340, y: 30, w: 54, d: 20 },
      mag: { style: 'curved', x: 380, w: 34, len: 120, curve: 34, y: 10, mat: 'blued' },
      fore: { style: 'plain', x0: 470, x1: 590, top: -16, bot: 18, mat: 'poly', r: 10 },
      barrel: { x0: 470, x1: 660, r: 6 }, muzzle: { style: 'bayonetlug', len: 14, r: 7 },
      gasTube: { x0: 480, x1: 600, h: 8 },
      rsight: { x: 210, h: 40, w: 22, y: -22 }, fsight: { x: 620, h: 36 },
      bolt: { style: 'tab', x: 560, y: -34, w: 16, h: 10 }, eject: { x: 350, y: -12 } },
  },
  {
    id: 'svd', name: 'Dragunov SVD', nickname: '', type: 'sniper',
    country: 'USSR', year: 1963, designer: 'Yevgeny Dragunov', eras: ['cold', 'modern'],
    wars: ['Soviet–Afghan War', 'Chechen Wars', 'Iraq War'],
    caliber: '7.62×54mmR', action: 'Gas-operated short-stroke piston, rotating bolt', capacity: 10,
    rpm: null, weight: '4.3 kg (with scope)', length: '1225 mm', velocity: '830 m/s', range: '800 m',
    modes: ['semi'], ammo: 'rifle',
    overview: 'A semi-automatic designated marksman rifle — meant to extend each infantry squad\'s reach rather than for lone snipers. Instantly recognisable by its skeletal thumbhole stock.',
    how: [
      'A short-stroke piston (not attached to the carrier) taps the carrier rearward.',
      'The bolt rotates to unlock, similar to the AK but with three lugs.',
      'The PSO-1 4× scope has a range-finding reticle and an illuminated grid.',
      'The skeleton stock saves weight while providing a firm cheek weld.',
    ],
    history: 'Selected in 1963 over a Konstantinov design. It fires the same 7.62×54mmR round as the 1891 Mosin, and is still in widespread service.',
    feel: { recoil: 7, loud: 9, text: 'A sharp kick of the full-power rimmed cartridge and a loud, cracking report. Fast follow-up shots.' },
    trivia: ['Can mount a bayonet — unusual for a precision rifle.'],
    sound: { ...P.full, mech: 'gas' },
    art: { kind: 'long',
      stock: { style: 'thumbhole', x0: 0, x1: 320, top: -10, bot: 84, mat: 'wood', cheek: true },
      rec: { x0: 320, x1: 540, top: -20, bot: 16, mat: 'blued', r: 3, port: [430, -12, 50, 12] },
      guard: { x: 410, w: 54, d: 22 },
      mag: { style: 'box', x: 440, w: 46, len: 80, ang: 8, mat: 'blued' },
      fore: { style: 'ak', x0: 540, x1: 720, top: -12, bot: 16, mat: 'wood', ut: -24, ux: 700 },
      barrel: { x0: 540, x1: 1040, r: 5 }, muzzle: { style: 'flash', len: 38, r: 7 },
      gasTube: { x0: 700, x1: 790, h: 8 },
      fsight: { x: 1010, h: 24 },
      optic: { style: 'pso', x0: 360, x1: 550, y: -54, base: -20 },
      bolt: { style: 'tab', x: 510, y: -10, w: 24, h: 9 }, eject: { x: 470, y: -14 } },
  },
  {
    id: 'm134', name: 'M134 Minigun', nickname: '"Puff the Magic Dragon" / "Painless gun"', type: 'mg',
    country: 'USA', year: 1963, designer: 'General Electric', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Iraq War', 'War in Afghanistan'],
    caliber: '7.62×51mm NATO', action: 'Electrically driven 6-barrel rotary (Gatling)', capacity: 3000,
    rpm: 3000, weight: '39 kg (gun & motor)', length: '801 mm', velocity: '853 m/s', range: '1000 m',
    modes: ['auto'], ammo: 'belt', rotary: true,
    overview: 'Six barrels spun by an electric motor fire 2,000–6,000 rounds per minute. Each barrel fires once per rotation, so none overheats.',
    how: [
      'An electric motor (not the cartridge) spins the barrel cluster — the gun needs external power.',
      'Each bolt rides a cam track, loading, firing and extracting as it goes around.',
      'Only one barrel fires at a time; the others are cooling, extracting or loading.',
      'It spins up for a fraction of a second before firing and spins down after release.',
    ],
    history: 'Developed for helicopter gunships and the AC-47 "Spooky" gunship in Vietnam. The sound is a continuous, motor-like roar — a single shot is impossible to hear.',
    feel: { recoil: 9, loud: 10, text: 'An unbroken, deafening ROAR like a chainsaw the size of a car. Too heavy to hold — vehicle or aircraft mounted.' },
    trivia: ['At 6,000 rpm it fires 100 rounds every second.'],
    sound: { power: 0.7, crack: 0.75, decay: 0.05, thump: 90, bright: 6000, tail: 0.9, mech: 'rotary' },
    art: { kind: 'rotary', housing: { x0: 100, x1: 420 }, barrels: { x1: 900, c1: 600, c2: 780 }, eject: { x: 260, y: 30 } },
  },
  {
    id: 'rem870', name: 'Remington 870', nickname: '', type: 'shotgun',
    country: 'USA', year: 1950, designer: 'Remington Arms', eras: ['cold', 'modern'],
    wars: ['Vietnam War', 'Gulf War', 'Iraq War'],
    caliber: '12 gauge', action: 'Pump action, tilting bolt', capacity: 6,
    rpm: null, weight: '3.6 kg', length: '1060 mm', velocity: '~400 m/s (buckshot)', range: '40 m',
    modes: ['pump'], ammo: 'shell',
    overview: 'The best-selling shotgun in history, with over 11 million made. Police, military and hunters favour it for rugged simplicity.',
    how: [
      'Shells load into a tube magazine under the barrel.',
      'Pull the fore-end back: twin action bars unlock the bolt and extract the spent hull.',
      'Push forward: a new shell is lifted and chambered — the iconic "chk-chk".',
      'Each 00 buckshot shell fires 8–9 pellets, each similar to a pistol bullet.',
    ],
    history: 'Introduced in 1950 and used by US Marines in Vietnam and by police across the world. The sound of a pump being racked is famous as a deterrent on its own.',
    feel: { recoil: 9, loud: 9, text: 'A massive, heavy BOOM and a hard shove into the shoulder, followed by the satisfying "chk-chk" of the pump.' },
    trivia: ['Twin action bars made it smoother and more durable than single-bar rivals.'],
    sound: P.shotgun,
    art: { kind: 'long',
      stock: { style: 'fixed', x0: 0, x1: 300, top: -6, bot: 76, mat: 'poly' },
      rec: { x0: 300, x1: 470, top: -18, bot: 22, mat: 'blued', r: 4, port: [380, -8, 60, 14] },
      grip: { x: 360, len: 74, ang: 22, w: 34, mat: 'poly' },
      guard: { x: 400, w: 54, d: 22 },
      tube: { x: 470, w: 14, len: 330, y: 9, mat: 'blued' },
      fore: { style: 'pump', x0: 520, x1: 680, top: 2, bot: 30, mat: 'poly', over: true },
      barrel: { x0: 470, x1: 930, r: 8 }, muzzle: { style: 'none' },
      fsight: { x: 920, h: 14 }, eject: { x: 410, y: -8 },
      extras: [['rect', 790, 6, 16, 22, 'blued', 3]] },
  },
  // ---------------------------------------------------------------- MODERN
  {
    id: 'aug', name: 'Steyr AUG', nickname: 'Armee-Universal-Gewehr', type: 'rifle',
    country: 'Austria', year: 1977, designer: 'Steyr Mannlicher', eras: ['cold', 'modern'],
    wars: ['East Timor (Australian F88)', 'War in Afghanistan', 'Iraq War'],
    caliber: '5.56×45mm NATO', action: 'Gas-operated short-stroke piston, rotating bolt, bullpup', capacity: 30,
    rpm: 700, weight: '3.6 kg', length: '790 mm', velocity: '970 m/s', range: '300 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A futuristic bullpup: the action sits behind the trigger, so a full-length barrel fits in a gun 20 cm shorter than an M16.',
    how: [
      'Bullpup layout: magazine and bolt are behind the pistol grip, inside the stock.',
      'Twin guide rods carry the bolt; a short-stroke piston drives them.',
      'Progressive trigger: half pull = single shot, full pull = automatic. No selector switch.',
      'Integrated 1.5× optic, translucent magazines and a barrel that swaps in seconds.',
    ],
    history: 'Adopted by Austria in 1977 and by Australia (F88), New Zealand, Ireland and many others. Its green polymer body made it look like science fiction in the 1970s.',
    feel: { recoil: 3, loud: 8, text: 'Recoil goes straight into the shoulder; the action next to your cheek makes it sound louder than other 5.56 rifles.' },
    trivia: ['Translucent magazines let you see how many rounds are left.'],
    sound: P.r556,
    art: { kind: 'long',
      rec: { x0: 0, x1: 560, top: -20, bot: 22, mat: 'olive', r: 8,
        shape: 'M0 -16 Q0 -22 8 -22 L540 -22 L560 -16 L560 22 L420 22 L400 48 L330 70 L40 70 Q0 70 0 52 Z' },
      grip: { x: 440, len: 74, ang: 12, w: 30, mat: 'olive' },
      guard: { x: 520, w: 120, d: 34, mat: 'olive' },
      mag: { style: 'curved', x: 190, w: 44, len: 110, curve: 30, y: 60, mat: 'clear', behind: true },
      vgrip: { x: 600, len: 66, y: 10, mat: 'olive' },
      barrel: { x0: 560, x1: 840, r: 6 }, muzzle: { style: 'flash', len: 34, r: 8 },
      fore: { style: 'plain', x0: 560, x1: 650, top: -14, bot: 14, mat: 'blued' },
      optic: { style: 'aug', x0: 200, x1: 480, y: -22, mat: 'olive' },
      bolt: { style: 'tab', x: 420, y: -18, w: 20, h: 8 }, eject: { x: 200, y: -14 },
      extras: [['rect', -10, -20, 12, 90, 'rubber', 4]] },
  },
  {
    id: 'm82a1', name: 'Barrett M82A1', nickname: 'The Light Fifty', type: 'sniper',
    country: 'USA', year: 1989, designer: 'Ronnie Barrett', eras: ['modern'],
    wars: ['Gulf War', 'Bosnian War', 'Iraq War', 'War in Afghanistan'],
    caliber: '.50 BMG (12.7×99mm NATO)', action: 'Short recoil, rotating bolt', capacity: 10,
    rpm: null, weight: '14 kg', length: '1448 mm', velocity: '853 m/s', range: '1800 m',
    modes: ['semi'], ammo: 'bmg',
    overview: 'An "anti-materiel" rifle that fires the same cartridge as the M2 heavy machine gun. Built to disable vehicles, radar and equipment at extreme range.',
    how: [
      'Barrel and bolt recoil together a short distance after firing.',
      'An accelerator arm then transfers energy to the bolt carrier, rotating and unlocking the bolt.',
      'The barrel returns forward while the bolt continues to extract and eject.',
      'The huge double-chamber muzzle brake redirects gas sideways, cutting recoil by up to ~70%.',
    ],
    history: 'Ronnie Barrett, a photographer, sketched it in his garage in 1980. The US military bought it in quantity for the 1991 Gulf War, where it was used against vehicles and equipment at long range.',
    feel: { recoil: 10, loud: 10, text: 'A concussive, chest-thumping BOOM. The muzzle brake blasts dust and pressure sideways — you feel it in your sternum.' },
    trivia: ['A .50 BMG round is about 14 cm long.', 'Designated M107 by the US Army in 2002.'],
    sound: P.bmg,
    art: { kind: 'long',
      stock: { style: 'skeleton', x0: 0, x1: 260, top: -24, bot: 76, mat: 'gunmetal' },
      rec: { x0: 260, x1: 760, top: -24, bot: 24, mat: 'gunmetal', r: 3, rail: [300, 700], port: [520, -12, 70, 14],
        lower: 'M330 24 L640 24 L640 50 L380 50 Z', lowerMat: 'gunmetal', lines: [[300, 0, 740, 0]] },
      grip: { x: 400, len: 78, ang: 22, w: 32, mat: 'poly', },
      guard: { x: 440, y: 50, w: 54, d: 22 },
      mag: { style: 'box', x: 540, w: 56, len: 90, y: 46, mat: 'dark' },
      fore: { style: 'plain', x0: 760, x1: 900, top: -14, bot: 14, mat: 'gunmetal' },
      barrel: { x0: 760, x1: 1220, r: 9, mat: 'blued' }, muzzle: { style: 'brake', len: 60, r: 12 },
      optic: { style: 'scope', x0: 380, x1: 700, y: -64, r: 11, eb: 18, ob: 22, base: -30, rings: [460, 600] },
      bipod: { x: 860, len: 120, y: 14, splay: 18 }, eject: { x: 555, y: -12 } },
  },
  {
    id: 'insas', name: 'INSAS Rifle', nickname: 'Indian Small Arms System', type: 'rifle',
    country: 'India', year: 1998, designer: 'ARDE / Ordnance Factory Board', eras: ['modern'],
    wars: ['Kargil War (1999)', 'Counter-insurgency operations'],
    caliber: '5.56×45mm NATO', action: 'Gas-operated long-stroke piston, rotating bolt', capacity: 30,
    rpm: 650, weight: '4.15 kg', length: '960 mm', velocity: '915 m/s', range: '400 m',
    modes: ['semi', 'burst'], ammo: 'rifle',
    overview: 'India\'s indigenous service rifle, replacing the 7.62 SLR. It blends AK-style internals with features from the FAL and other designs, and uses translucent polymer magazines.',
    how: [
      'Long-stroke gas piston and rotating bolt, much like the AK family.',
      'A manual gas regulator (also used to launch rifle grenades).',
      'Selector offers single shot and 3-round burst — automatic fire was omitted to conserve ammunition.',
      'Translucent 20/30-round magazines show remaining ammunition.',
    ],
    history: 'Development began in the 1980s; it entered service in 1998 and saw its first major combat in the 1999 Kargil War. It is gradually being supplemented by newer rifles such as the AK-203 and SIG716.',
    feel: { recoil: 4, loud: 8, text: 'Mild 5.56 recoil in a fairly heavy rifle; a sharp crack and the triple-tap rhythm of its burst mode.' },
    trivia: ['The family includes a light machine gun (LMG) with a longer, heavier barrel.'],
    sound: P.r556,
    art: { kind: 'long',
      stock: { style: 'fixed', x0: 0, x1: 240, top: 0, bot: 70, mat: 'poly' },
      rec: { x0: 240, x1: 560, top: -18, bot: 20, mat: 'blued', r: 2, port: [430, -10, 60, 10] },
      grip: { x: 310, len: 76, ang: 16, w: 30, mat: 'poly' },
      guard: { x: 360, w: 54, d: 22 },
      mag: { style: 'curved', x: 405, w: 42, len: 120, curve: 34, mat: 'clear' },
      fore: { style: 'ak', x0: 560, x1: 730, top: -10, bot: 18, mat: 'poly', ut: -26, ux: 710 },
      gasTube: { x0: 710, x1: 800, h: 9 },
      barrel: { x0: 560, x1: 940, r: 5 }, muzzle: { style: 'flash', len: 34, r: 8 },
      fsight: { x: 900, h: 32 }, rsight: { x: 260, h: 34, w: 20, y: -18 },
      bolt: { style: 'tab', x: 520, y: -6, w: 24, h: 9 }, eject: { x: 460, y: -18 },
      extras: [['rect', 255, -38, 70, 10, 'poly', 3]] },
  },
  {
    id: 'm4a1', name: 'Colt M4A1 Carbine', nickname: '', type: 'rifle',
    country: 'USA', year: 1994, designer: 'Colt (from Stoner\'s AR-15)', eras: ['modern'],
    wars: ['War in Afghanistan', 'Iraq War', 'Operation Inherent Resolve'],
    caliber: '5.56×45mm NATO', action: 'Direct impingement gas, rotating bolt', capacity: 30,
    rpm: 800, weight: '2.9 kg (empty)', length: '838 mm (stock extended)', velocity: '910 m/s', range: '500 m',
    modes: ['semi', 'auto'], ammo: 'rifle',
    overview: 'A shortened, modular M16 with a collapsible stock and Picatinny rails for optics, lights and lasers. The standard carbine of US forces in the 21st century.',
    how: [
      'Direct-impingement gas system like the M16, with a shorter carbine-length gas tube.',
      'Collapsible stock adjusts for body armour and different shooters.',
      'Rails accept red-dot sights, magnifiers, lasers and lights.',
      'The A1 replaced the M4\'s 3-round burst with fully automatic fire.',
    ],
    history: 'Entered service in 1994 and became the US Army\'s primary weapon after 2010. The shorter barrel trades a little velocity for handiness in vehicles and buildings.',
    feel: { recoil: 3, loud: 9, text: 'Light, fast recoil; the short barrel makes a louder, harsher crack and a bigger flash than the M16.' },
    trivia: ['Over 500,000 have been issued to US forces.'],
    sound: { ...P.r556, power: 0.62, bright: 9500 },
    art: { kind: 'long',
      stock: { style: 'tube', x0: 0, x1: 250, top: -16, bot: 52, mat: 'poly' },
      rec: { x0: 250, x1: 480, top: -22, bot: 18, mat: 'poly', r: 3, rail: [254, 476], port: [380, -12, 48, 12],
        lower: 'M270 18 L440 18 L440 36 L270 36 Z', lowerMat: 'poly' },
      grip: { x: 330, len: 76, ang: 20, w: 30, mat: 'poly' },
      guard: { x: 375, y: 36, w: 54, d: 20 },
      mag: { style: 'curved', x: 400, w: 42, len: 120, curve: 22, y: 32, mat: 'tan' },
      fore: { style: 'rail', x0: 480, x1: 690, top: -20, bot: 18, mat: 'poly' },
      barrel: { x0: 480, x1: 810, r: 5 }, muzzle: { style: 'flash', len: 34, r: 7 },
      fsight: { x: 700, h: 46 },
      optic: { style: 'reddot', x0: 300, y: -30 },
      vgrip: { x: 600, len: 60, y: 18, mat: 'poly' },
      eject: { x: 400, y: -12 } },
  },
  {
    id: 'm107a1', name: 'Barrett M107A1', nickname: '', type: 'sniper',
    country: 'USA', year: 2011, designer: 'Barrett Firearms', eras: ['modern'],
    wars: ['War in Afghanistan', 'Operation Inherent Resolve'],
    caliber: '.50 BMG (12.7×99mm NATO)', action: 'Short recoil, rotating bolt', capacity: 10,
    rpm: null, weight: '13 kg', length: '1448 mm', velocity: '853 m/s', range: '1800 m',
    modes: ['semi'], ammo: 'bmg',
    overview: 'A lighter, suppressor-ready evolution of the M82/M107 with a titanium muzzle brake, improved bolt carrier and a cylindrical barrel-recoil system.',
    how: [
      'Short-recoil action: barrel and bolt move back together before an accelerator unlocks the bolt.',
      'A new four-port cylindrical brake is designed to also take a suppressor.',
      'Weighs about 2.3 kg less than the M107 through titanium and aluminium parts.',
      'A monopod under the stock and an adjustable bipod give stable long-range shooting.',
    ],
    history: 'Introduced in 2011 to offer the M107\'s power with less weight and with suppressor compatibility — a major change for a .50 calibre rifle.',
    feel: { recoil: 9, loud: 10, text: 'Still a huge, concussive blast, but the recoil system and brake make it surprisingly manageable for its power.' },
    trivia: ['Its brake is about the size of a soda can.'],
    sound: { ...P.bmg, decay: 0.42 },
    art: { kind: 'long',
      stock: { style: 'skeleton', x0: 0, x1: 260, top: -24, bot: 76, mat: 'gunmetal', cheek: true },
      rec: { x0: 260, x1: 760, top: -24, bot: 24, mat: 'gunmetal', r: 3, rail: [300, 740], port: [520, -12, 70, 14],
        lower: 'M330 24 L640 24 L640 50 L380 50 Z', lowerMat: 'gunmetal', lines: [[300, 0, 740, 0]] },
      grip: { x: 400, len: 78, ang: 20, w: 32, mat: 'poly' },
      guard: { x: 440, y: 50, w: 54, d: 22 },
      mag: { style: 'box', x: 540, w: 56, len: 90, y: 46, mat: 'dark' },
      fore: { style: 'mlok', x0: 760, x1: 940, top: -18, bot: 18, mat: 'gunmetal' },
      barrel: { x0: 760, x1: 1200, r: 9, mat: 'blued' }, muzzle: { style: 'comp', len: 80, r: 15 },
      optic: { style: 'scope', x0: 380, x1: 720, y: -66, r: 12, eb: 19, ob: 24, base: -30, rings: [470, 610] },
      bipod: { x: 880, len: 120, y: 14, splay: 18 },
      vgrip: { x: 120, len: 50, y: 60, mat: 'blued' }, eject: { x: 555, y: -12 } },
  },
];

export const byId = Object.fromEntries(WEAPONS.map((w) => [w.id, w]));
